- CHANGELOG.md
- README.md
- seslib/__init__.py
- seslib/templates/Vagrantfile.j2
Several improvements to the docs and one config setting:
Use `libvirt_use_ssh` instead `libvirt_use_ssl`.
Added Fedora Linux installation instructions.
Added hints on how to configure remote SSH access.
Improved formatting and wording in a couple of places.
Signed-off-by: Lenz Grimmer <lenz@grimmer.com>
> README.md: extended installation/configuration

- .gitignore
- README.md
- setup.py
Address the following error:
```
smithfarm@vanguard1:~> sesdev create ses6 --single-node mini
Traceback (most recent call last):
File "/usr/bin/sesdev", line 11, in <module>
load_entry_point('sesdev==1.0.0+1573749027.g0e3c988', 'console_scripts', 'sesdev')()
File "/usr/lib/python3.6/site-packages/sesdev.py", line 16, in sesdev_main
cli(prog_name='sesdev')
File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
return …
```
> setup.py: add missing template directories

- setup.py
b9e55088fe7f8603222a06a83b94da11203687c5 fixed the deepsea templates packaging,
but the engine/libvirt templates are still missing in the RPM package.
> setup.py: fix engine/libvirt template directory

- seslib/__init__.py
Now that SES7 development is underway, upstream master is currently the go-to
place for the latest, greatest code. For SUSE, the best place to get to that
is "filesystems:ceph:master:upstream" on OBS (even for sles-12-sp2).
> seslib/VERSION_OS_REPO_MAPPING: use filesystems:ceph:master:upstream

- .github/workflows/obs-publish.yml
- CHANGELOG.md
This action will be triggered on a release creation and
will publish a new package revision in OBS.
Signed-off-by: Tiago Melo <tmelo@suse.com>
> Add Github Action to publish to OBS

- seslib/tools.py
> seslib: fix 100% cpu usage in non-block stdout reading

- README.md
- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/Vagrantfile.j2
This commit provides a way to turn off the current behavior where sesdev adds
custom repos with an elevated priority.
Also, it drops the setting of elevated priority on repos hard-coded in
VERSION_OS_REPO_MAPPING. These repos are controlled by package maintainers and
are not expected to need elevated priority.
Fixes: https://github.com/rjfd/sesdev/issues/18
> Implement --repo-priority / --no-repo-priority

- sesdev/__init__.py
In other words, add openattic role only when --single-node is given.
Fixes: https://github.com/rjfd/sesdev/issues/21
> When deploying ses5 with explicit --roles, do not add openattic

- sesdev/__init__.py
Before 42a541c735d1f3a015b0c22a904d0a0ec2a760f5, --single-node was working fine.
After, it was broken:
```
(v) smithfarm@vanguard1:~/sesdev> sesdev create ses6 --single-node mini
=== Creating deployment with the following configuration ===
Deployment VMs:
-- node1:
- OS:               sles-15-sp1
- ses_version:      ses6
- roles:            ['grafana', 'ganesha ]', 'prometheus', 'mds', 'mon', 'igw', 'rgw', 'mgr', '[   admin', 'storage']
```
Fixes: 42a541c735d1f3a015b0c22a904d0a0ec2a760f5
Fixes: https://github.com/rjfd/sesdev/issues/25
> Fix --single-node regression

- sesdev/__init__.py
Adds the name of the node to the informational output that is printed when `sesdev tunnel` is called.
Before:
```
$ sesdev tunnel nautilus-singlenode dashboard
Opening tunnel to service 'dashboard'...
```
After:
```
$ sesdev tunnel nautilus-singlenode dashboard
Opening tunnel to service 'dashboard' on node 'admin'...
```
Signed-off-by: Lenz Grimmer <lenz@grimmer.com>
> Add node info to SSH tunnel command

- seslib/__init__.py
Adds the number of VMs in a deployment to the status output.
Signed-off-by: Lenz Grimmer <lenz@grimmer.com>
> Display amount of deployed VMs in status output

- README.md
Updated the `README.md` to list all available node roles and services that can be used for SSH tunneling.
Signed-off-by: Lenz Grimmer <lenz@grimmer.com>
> README.md: Added info about roles and services

- seslib/templates/provision.sh.j2
As a convenience, let users of sesdev install and display manpages inside their clusters.
> Enable display of manpages

- seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
I've had the odd experience that `zypper in` failed, but bootstrapping continued.
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>
> RFC: ceph_bootstrap_deployment.sh: Also set -e

- seslib/__init__.py
The "standard" repo is missing a bunch of packages that are needed for SES7
deployment.
Signed-off-by: Ricardo Dias <ricardo.dias@suse.com>
> Use SES7 Media1 repo instead of "standard"

- .gitignore
- .travis.yml
- tox.ini
Add very basic testing when doing pull requests via TravisCI and
tox. The tests can also be executed manually with eg. "tox -elint" for
the linters.
> Enable linter via travis

- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
Since https://github.com/SUSE/ceph-bootstrap/pull/26, https://github.com/suse/ceph-salt-formula was moved to https://github.com/suse/ceph-bootstrap.
> ceph-bootstrap: 'ceph-salt-formula' moved to 'ceph-bootstrap'

- sesdev/__init__.py
I've previously forgotten to adapt the text in the example when I removed the non-working `--deepsea` argument in favor of an example not deployed by deepsea.
> fix example in help of CLI

- seslib/__init__.py
- seslib/templates/provision.sh.j2
Since the "ceph" package gets deleted from Devel:Storage:7.0 as soon
as it gets accepted into SUSE:SLE-15-SP2:Update:Products:SES7, we need
both repos to ensure that all ses7 packages will be available.
> provision: fix ses7 repos

- seslib/templates/engine/libvirt/vagrant.node.j2
Fixes: https://github.com/SUSE/sesdev/issues/48
> vagrant: generate random serial number for each attached disk

- seslib/__init__.py
Fix a regression introduced in https://github.com/SUSE/sesdev/pull/39 where all nodes have the same `*.200` IP address.
> Fix node ip generation

- HOWTORELEASE.md
This file is adapted from the same file over at the `ceph-bootstrap` project.
> HOWTORELEASE.md: add new documentation file

- sesdev/__init__.py
The old way would silently override some `--num-disk=X` settings. Also, when num_disks was not set explicitly by the user, the tool would set it too low for 1- and 2-node clusters.
> Revamp --num-disks handling

- .travis.yml
- README.md
- sesdev.spec
- sesdev/__init__.py
- seslib/__init__.py
- setup.cfg
Fixes: https://github.com/SUSE/sesdev/issues/58
---
TO DO:
> Implement "vagrant box list" and "vagrant box remove"

- seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
- seslib/templates/provision.sh.j2
One of the fixes guarantees that when ceph daemons generate their metadata, the `hostname` info will have the short hostname of the machine, which will match the ceph orchestrator inventory.
It also fixes the drive-groups spec generation to match the requirements of ceph 15.1.0 version.
> several fixes for octopus/ses7 deployment

- seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
Since https://github.com/SUSE/ceph-bootstrap/pull/61, the pillar is automatically configured.
> Pillar is now automatically configured by ceph-bootstrap

- .pylintrc
- README.md
After the introduction of the libvirt dependency, there were reports
that local "tox -elint" started failing with:
seslib/__init__.py:12:0: E0401: Unable to import 'libvirt' (import-error)
even though libvirt module is installed in the virtualenv.
> pylintrc: ignore libvirt module

- seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
- seslib/templates/provision.sh.j2
Since https://github.com/SUSE/ceph-bootstrap/pull/61, the pillar is automatically configured.
---
The test.ping loop is applicable to all environments, not just
ceph-bootstrap ones.
> [AFTER: M4 RELEASE] Pillar is now automatically configured by ceph-bootstrap

- seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
The ceph-salt-formula state files are installed in a custom directory
that is configured in an additional configuration file stored in
/etc/salt/master.d and the salt-master needs to be restarted to load
the state files in that custom directory.
> ceph_bootstrap: restart salt-master after ceph-bootstrap installation

- seslib/__init__.py
When a package (such as "ceph") is promoted from Devel:Storage:7.0 to
SUSE:SLE-15-SP2:Update:Products:SES7, it gets automatically deleted from
Devel:Storage:7.0 when the associated SR is accepted.
This creates a race condition: due to the way the Build Service works,
the next Devel:Storage:7.0 image build after the package "disappears"
typically does not get the latest package from
SUSE:SLE-15-SP2:Update:Products:SES7 (to where it was promoted), because
the package in that project is still building. This is an especially big
problem with the package "ceph", because it takes a long time to build.
By including both image repos - Devel:Storage:7.0 and
SUSE:SLE-15-SP2:Update:Products:SES7 - we mitigate the damage caused by
this race condition. Chances are that _one_ of these two will have the …
> Increase chances of getting the latest ses7 packages

- seslib/__init__.py
- seslib/exceptions.py
Without this patch, the command
sesdev create ses7 --qa-test ses7_test1
fails because it cannot find ceph-bootstrap-qa.
The package ceph-bootstrap-qa is available on the SES7 Internal Media.
> [AFTER: #84] seslib: add SES7 Internal Media when --qa-test given

- seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
This information is logged to facilitate faster debugging of problems
arising out of incompatibility between cephadm and ceph-bootstrap.
Fixes: https://github.com/SUSE/sesdev/issues/85
> ceph_bootstrap_deployment: log cephadm and ceph-bootstrap version

- seslib/__init__.py
enabled here: https://github.com/vagrant-libvirt/vagrant-libvirt/pull/708/commits/04b34f8c13f824129b1addb1d21c685f0203da75
Will enable 'autostart' in the libvirt network configuration.
Signed-off-by: Joshua Schmid <jschmid@suse.de>
> libvirt/network: autostart networks per default

- sesdev/__init__.py
- seslib/__init__.py
Handle the following edge case:
An existing deployment has one or more node snapshot images and/or disk
volume images, but no base box image. As a result, the deployment is
registered as "not deployed".
Without this patch, running "sesdev destroy" on that deployment will not
trigger "vagrant destroy" and all the images still existing and associated 
with that deployment will be left behind. Then, when the user tries to create 
another deployment with the same deployment ID, vagrant will complain 
like so:
"Volume for domain is already created. Please run 'vagrant destroy' first."
However, the user is not expected to be able to run "vagrant destroy"
("sesdev destroy" is supposed to do that for him).
> Remove any orphaned images after destroy

- seslib/exceptions.py
- seslib/tools.py
When the command it is running fails, "run_async" captures whatever
got written to stderr as a sequence of bytes.
Make sure we decode these bytes before sending them to CmdException.
> tools/run_async: decode stderr bytes

- seslib/templates/deepsea/deepsea_deployment.sh.j2
I tried to deploy nautilus and ran into the same bug we've seen
elsewhere: sometimes, test.ping does not succeed on the first try
and it has to be repeated.
> deepsea_deployment.sh: try test.ping in a loop

- seslib/templates/provision.sh.j2
This fixes the issues that after the salt-master is setup and installed the minion on the master doesn't work and test.ping fails. If we do another salt-minion restart after the master is configured it works now.
Signed-off-by: Kai Wagner <kwagner@suse.com>
> added another salt-minion restart after salt-master installation

- seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
- seslib/templates/provision.sh.j2
With these patches, a functioning NTP server setup is deployed on the admin node before DeepSea starts, and DeepSea is instructed -- via `time_init: ntp` to configure NTPD on all the cluster nodes, pointing at the admin node.
Unfortunately, DeepSea has to be patched for this to work...
Fixes: https://github.com/SUSE/sesdev/issues/107
> Fix NTP issue that was causing SES5 deployment to fail

- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/caasp/loadbalancer.sh.j2
- seslib/templates/caasp/master.sh.j2
- seslib/templates/caasp/provision.sh.j2
- seslib/templates/caasp/storage.sh.j2
- seslib/templates/provision.sh.j2
- setup.cfg
Ricardo and I added the possibility to do a CaaSP deployment with sesdev. 
You can now either just spawn a completely configured CaaSP environment for development purposes or you could also directly add rook+ceph on top of it.
Example:
`sesdev create caasp4 caasp4` (gives you just a CaaSP cluster)
`sesdev create caasp4 caasp4 --deploy-ses` (gives you a CaaSP cluster with already rook+Ceph on top)`
If you want to have multiple workers or master you could work with the `--roles` option as follows:
`--roles="[master],[worker],[worker],[loadbalancer],[storage]"`
Signed-off-by: Kai Wagner <kwagner@suse.com>
> CaaSP setup

- seslib/templates/provision.sh.j2
If we include "which", it's easy for developers to assume that it's
always available everywhere, which is not true.
---
Tested does not break:
> provision: remove which RPM from test environment

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Since https://github.com/ceph/ceph-salt/pull/76 was merged, sesdev
can no longer deploy ceph on an even slightly out-of-date Vagrant
box. Instead, it displays a message:
```
Salt master must be rebooted manually
```
and refuses to continue.
Since sesdev already has the `sesdev box remove` feature for updating
out-of-date Vagrant Boxes, and because the ceph-salt update
functionality effectively prevents automated deployment of Ceph by
sesdev, disable ceph-salt's automated system update/reboot feature.
> ceph_salt_deployment: disable system update and reboot

- sesdev/__init__.py
If I want ceph-salt to run `cephadm bootstrap`, but stop before deploying any further daemons, there is not currently any way to achieve that with sesdev. This is a bug, and it is fixed by this PR.
Fixes: https://github.com/SUSE/sesdev/issues/119
> sesdev: give the user a way to specify --no-deploy-*

- sesdev/__init__.py
When running into an exception, do return 1 and return that. This is
needed eg. for CI.
Fixes: #126
> Return with a non-zero exit code in a failure case

- seslib/__init__.py
- seslib/templates/provision.sh.j2
We have a rule of thumb that, in the deployment, the following commands
should show the same version of ceph:
ceph --version    # host ceph version
ceph versions     # container ceph version
But currently that is not the case for "sesdev create {ses7,octopus}", unless
the default container path is overrided. This patch should fix it.
> seslib: correct downstream container for "sesdev create {ses7,octopus}"

- qa/common/common.sh
- qa/common/helper.sh
- qa/health-ok.sh
It's possible that a completely different version of ceph is running in
the containers than on the host. Add a check for that to the QA suite.
> qa: assert "ceph versions" matches "ceph --version"

- seslib/templates/provision.sh.j2
> provision.sh: remove Python 2 so it doesn't pollute the environment

- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/Vagrantfile.j2
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Even if the user does not give --qa-test on the "sesdev create" command
line, set up a script on each VM which can be triggered after initial
deployment.
And go even a step further and provide a "sesdev qa-test" command
for triggering the script.
Fixes: https://github.com/SUSE/sesdev/issues/128
> Implement "sesdev qa-test" command

- seslib/templates/provision.sh.j2
It's frustrating to have to figure out which RPM needs to be installed
in order to get the "cnf" command...
Also, take this opportunity to tweak the Jinja code for better
maintainability.
> provision: install "command-not-found", "supportutils", etc. in test environments

- sesdev.spec
According to
https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/#_automatically_generated_dependencies
"Packages MAY use the automatic Python dependency generator."
"This generator is enabled by default in Fedora. If a packager wishes to
explicitly opt out of the generator . . ., a packager SHOULD opt out
explicitly by adding:
%{?python_disable_dependency_generator}
Although this statement can be used anywhere in the spec, we recommend
putting it just before the main package’s %description declaration."
As maintainer of the upstream spec file, I want to opt out, because
I prefer to explicitly declare (and track) the dependencies in the spec
file.
The dependencies defined in `setup.cfg` are used when sesdev is installed using `pip`.
The dependencies defined in `sesdev.spec` …
> spec: disable RH/Fedora Python dependendency generator

- seslib/__init__.py
When running sesdev (and sesdev-qa) installed from RPM, I hit a bug
- sesdev is trying to find the qa scripts at the wrong path!
> qa: fix path to qa scripts for RPM case

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
This fixes a bug that has been present since the very beginning.
Fixes: c6cdd7339952671c6c2fbf7184711da8a488a01c
Fixes: https://github.com/SUSE/sesdev/issues/142
> ceph_salt_deployment: honor --no-deploy-osds option

- sesdev/__init__.py
- seslib/__init__.py
With this patch, we get debug-level output from "vagrant up" and
"vagrant destroy", but only when the command fails.
When the command succeeds, vagrant sends the debug messages to stderr
and these are ignored by run_async.
Still, this is better than no debug messages at all when vagrant fails.
> Let --debug run "vagrant up/destroy" in debug mode

- seslib/__init__.py
sesdev was only guessing the device names here - in reality, it has no
control over the device names.
Fixes: https://github.com/SUSE/sesdev/issues/30
> seslib: stop printing misleading device names

- README.md
- sesdev/__init__.py
- seslib/__init__.py
- seslib/exceptions.py
- seslib/templates/Vagrantfile.j2
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
- seslib/templates/deepsea/deepsea_deployment.sh.j2
- seslib/templates/deepsea/nautilus_policy.cfg.j2
- seslib/templates/deepsea/nautilus_pre_stage_0.sh.j2
- seslib/templates/deepsea/ses5_policy.cfg.j2
- seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
- seslib/templates/provision.sh.j2
Fixes: https://github.com/SUSE/sesdev/issues/160
---
To Do:
> Change "admin" role semantics and make roles configurable

- README.md
Useful to have a direct link to the current master build.
> doc: Add Jenkins build status badge to README

- sesdev.spec
- seslib/templates/Vagrantfile.j2
sesdev is known to require a recent vagrant version, but it's not
entirely clear how recent.
From https://github.com/SUSE/sesdev/issues/155 we know that 2.2.0 will
not work.
Virtualization:vagrant/vagrant was updated to 2.2.2 on January 4, 2019.
This is probably also too old, so enforce vagrant > 2.2.2
> Vagrantfile,sesdev.spec: require vagrant > 2.2.2

- Jenkinsfile.integration
Some builds seem to hang forever. Adding a timeout makes sure that we
don't pay for endless running servers.
> Jenkinsfile.integration: Add timeout for "sesdev create"

- README.md
- seslib/__init__.py
The upstream "octopus" branch was recently split from "master", so there
is no longer any reason to track the latter branch.
> Use "filesystems:ceph:octopus:upstream" for default cephadm/container build

- seslib/templates/provision.sh.j2
After some recent refactoring, the `ca-certificates-suse` package was no longer getting installed on `ses5` and `sesdev` was not raising it as an error.
This patchset fixes both issues.
> provision.sh: add SUSE:CA repo on ses5

- seslib/templates/provision.sh.j2
Fixes: https://github.com/SUSE/sesdev/issues/172
> provision.sh: do not fail ses5 deployment if ntp not installed

- sesdev/__init__.py
- seslib/__init__.py
- seslib/exceptions.py
Fixes: https://github.com/SUSE/sesdev/issues/75
---
To Do:
> Implement feature: "sesdev supportconfig DEPLOYMENT_ID NODE_ID"

- Jenkinsfile.integration
That way, we can trigger the job also manually or from other jobs with
a specific ceph-salt repo.
> Jenkinsfile.integration: Parametrize ceph-salt repo and branch

- qa/common/common.sh
- qa/health-ok.sh
After a recent round of refactoring, it started taking a longer time for
the cluster to become aware of newly added OSD nodes. As a result,
number_of_nodes_actual_vs_expected_test was failing because the script
was going too fast. This commit causes the script to wait, if necessary,
for up to 5 minutes for the OSD node(s) to show up.
> qa/health-ok.sh: wait for OSD nodes to show up

- Jenkinsfile.integration
That's useful if the job gets triggered by another job and we want to
adjust the name and description in that case.
> Jenkinsfile.integration: Be able to set custom job name/desc

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Set "osd crush chooseleaf type = 0"
After https://github.com/ceph/ceph-salt/pull/129
> Set "osd crush chooseleaf type = 0" via bootstrap ceph.conf in very small clusters

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Fetch also the available github PRs when installing ceph-salt from
source. With that, it's possible to git "ceph_salt_git_branch" a value
like "origin/pr/127" which will then checkout the github pull request
127 and use that for installation.
That is useful for testing pull requests against ceph-salt together
with sesdev.
> ceph_salt_deployment.sh: Fetch github PRs when installing from src

- bootstrap.sh
Under some circumstances that are not 100% clear to me -- for example
when virtualenv is coming from the python2-virtualenv RPM -- virtualenv
might default to Python 2 even though Python 3 is also installed in the
system.
Fixes: https://github.com/SUSE/sesdev/issues/194
> bootstrap.sh: explicitly use python3

- Jenkinsfile.integration
Instead of seeing the color codes as ascii in the logs, use the
"ansiColor" Jenkins plugin to have more readable output.
> Jenkinsfile.integration: Add colorful output when running sesdev

- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/deepsea/deepsea_deployment.sh.j2
When this option is given, sesdev will try to deploy encrypted OSDs.
Fixes: https://github.com/SUSE/sesdev/issues/188
> Implement --encrypted-osds feature

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
At some point in the near future, "ceph-salt deploy" will no longer
deploy OSDs (or, for that matter, any other daemons except for those
deployed by "cephadm bootstrap".
It behooves us to start preparing for that sooner rather than later.
> ceph_salt_deployment: move OSD deployment to sesdev

- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
At some point in the near future, "ceph-salt deploy" will no longer
deploy MONs or MGRs except for those deployed by "cephadm bootstrap".
It behooves us to start preparing for that sooner rather than later.
> ceph_salt_deployment: use sesdev to deploy MONs and MGRs

- sesdev/__init__.py
It was not clear whether to use "--force" or "--non-interactive". Some
commands expected one, others expected the other.
Make them all accept them all.
> sesdev: uniform --force/--non-interactive

- README.md
- sesdev/__init__.py
- seslib/__init__.py
- seslib/exceptions.py
A check that quickly bails out if someone omits the "master" role was
implemented by ddd4d91 but that commit
is being reverted and replaced by this solution which implements the
check in a less intrusive way, later in the "sesdev create" process.
> seslib: raise exception if more, or less, than one master/bootstrap role

- Jenkinsfile.integration
This provides more clarity, simply by looking at the Jenkins pipeline
diagram, whether the job failed in creating the cluster or in the
subsequent QA test phase.
> Jenkinsfile.integration: split qa-test into separate stage

- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/Vagrantfile.j2
- seslib/templates/provision.sh.j2
For each deployment, sesdev generates an SSH keypair and:
1. uploads it as /home/vagrant/.ssh/id_rsa{.pub} to all the VMs
2. copies it to /root/.ssh/id_rsa{.pub}
3. appends the public part to /home/vagrant/.ssh/authorized_keys
4. appends the public part of /root/.ssh/authorized_keys
This is problematic because /root/.ssh/id_rsa{.pub} is prone to being
rewritten by "other software" (e.g. ceph-salt was rewriting it).
This patch makes sesdev install its keypair under a different name:
".ssh/sesdev{.pub}".
To avoid losing the ability to ssh from any node of the cluster to any
other node simply by issuing the command "ssh $NODE_ID" as root, we
create "/root/.ssh/id_rsa{.pub}" as a symlink to sesdev's keypair.
Fixes: https://github.com/SUSE/sesdev/issues/206
> seslib: install sesdev-generated keypair under non-default name

- Jenkinsfile.integration
In case the node delete fails, retry it. We don't want to have running
nodes on OVH after a job finished.
> Jenkinsfile.integration: Retry jenkins slave deletion

- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Before, one had to provide both "--ceph-salt-repo" and
"--ceph-salt-branch" in order for sesdev to install ceph-salt from
source.
With this patch, only one or the other is required. When one of these
two options is given, the other will default to a sensible value.
The defaults are hard-coded to:
--ceph-salt-repo https://github.com/ceph/ceph-salt
--ceph-salt-branch master
> ceph_salt_deployment: make it easier to install ceph-salt from source

- seslib/__init__.py
- seslib/templates/deepsea/deepsea_deployment.sh.j2
Stage 4 is not needed, and is a noop, on basic "MON, MGR, OSD" clusters, so omit it in such cases.
> deepsea_deployment: run Stage 4 only if justified by roles

- seslib/__init__.py
231e50d41c62a8c62485fd59b3ca79503cd264c2 changed the default value of
this setting to None, which caused a regression.
Fixes: 231e50d41c62a8c62485fd59b3ca79503cd264c2
Fixes: https://github.com/SUSE/sesdev/issues/216
> seslib: ceph_salt_git_branch might be None

- seslib/__init__.py
When string variables are set to None, we can easily fall into a trap
like this:
```
File "/home/tom/devel/suse/sesdev/seslib/__init__.py", line 1082, in generate_vagrantfile
if self.settings.ceph_salt_git_branch.startswith('origin/pr/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
Fixes: https://github.com/SUSE/sesdev/issues/216
> seslib: make all str-type settings default to the empty string

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
- seslib/templates/deepsea/deepsea_deployment.sh.j2
Deployment fails with:
master: ++ ceph-salt config /Ceph_Cluster/Minions add master.octopus.com
master: /tmp/vagrant-shell: line 143: ceph-salt: command not found
Yet, after subsequently SSHing in:
master:~ # type ceph-salt
ceph-salt is /usr/local/bin/ceph-salt
master:~ # echo $PATH
/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin
master:~ # ceph-salt
Usage: ceph-salt [OPTIONS] COMMAND [ARGS]...
...
The reason is that `ceph_salt_deployment.sh` is not running in a login shell, so `/usr/local/bin` does not get added to the PATH.
For whatever reason, `pip install` does not behave this way in Leap 15.2 and earlier. This issue is only seen in `--os=tumbleweed` deployments.
Fixes: https://github.com/SUSE/sesdev/issues/220
> ceph_salt_deployment: use --prefix /usr with "pip install"

- README.md
When we install sesdev from source, it is nice to know beforehard
all the packages we need to have for a particular distribution.
We list all necessary packages for Debian, Ubuntu, Fedora, and
openSUSE Leap 15.1/15.2.
> README.md: Needed packages for all major distros

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Adapt to https://github.com/ceph/ceph-salt/pull/166
> [AFTER ceph/ceph-salt#166] ceph-salt is now using lower-case on config nodes

- seslib/templates/deepsea/deepsea_deployment.sh.j2
Harden the script by checking if /srv/salt/ceph/configuration/files/drive_groups.yml exists.
Fixes: https://github.com/SUSE/sesdev/issues/228
Signed-off-by: Volker Theile <vtheile@suse.com>
> Failed to setup a SES5 single-node cluster

- seslib/__init__.py
The DeepSea version that is shipped with SES5 does not have any
"prometheus" or "grafana" roles. It always deploys these services and
there is no easy way to prevent it from doing that.
For port-forwarding purposes, sesdev forces the grafana node to be
"master" in ses5 deployments, and it should have been doing this for
prometheus as well.
Fixes: https://github.com/SUSE/sesdev/issues/231
> seslib: force ses5 prometheus node to master

- README.md
- sesdev/__init__.py
- seslib/__init__.py
- seslib/exceptions.py
Unfortunately, this change has gone through several iterations already.
I think I finally have it right this time.
This commit more-or-less reverts/replaces the following three commits:
"seslib: check bootstrap role only when it is relevant"
5100786d82de471146223182a9d30ded9c0491d7
"seslib: raise exception more, or less, than one master/bootstrap role"
a52f94eb3faa24fe1505cf8f6ded620f743d8f52
"sesdev: fail when master role is missing"
ddd4d91ca08f3e4ea993d9cba9431373c62fed8b
It introduces a new "vet_configuration" method in the "Deployment" class, explicitly for the purpose of vetting roles, and concentrates all of the role vetting code into that method.
> seslib: systemically vet roles on create

- .gitignore
- contrib/run-standalone.sh
- contrib/standalone.sh
- qa/common/json.sh
- seslib/__init__.py
- seslib/templates/Vagrantfile.j2
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
- seslib/templates/deepsea/deepsea_deployment.sh.j2
- seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
- seslib/templates/provision.sh.j2
- seslib/templates/qa_test.sh
- seslib/templates/sync_clocks.sh.j2
Until now, `--qa-test` and `sesdev qa-test` have only worked when ceph-salt is used for deployment, but there is no good reason for that.
> templates: extend --qa-test to DeepSea-deployed versions and fix issues preventing it from passing

- README.md
- sesdev/__init__.py
When one is accustomed to creating and destroying lots of clusters,
it can be tiresome to type in the deployment_id argument, always the
same one, for each invocation.
Make the argument optional and have it default to something sane.
> sesdev: make deployment_id argument optional

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
As of https://github.com/ceph/ceph-salt/pull/157 ceph-salt should take
care of this itself.
Also, since these steps might not be included in the documentation, it's
possible that a user will omit them and run into bugs that, because of
these two lines, are not seen with sesdev.
> ceph_salt_deployment.sh: do not refresh/sync pillar data

- seslib/templates/provision.sh.j2
The SLE-12-SP3 Vagrant Box has newer versions of the python-base,
python-xml, libncurses5, and libncurses6 packages than are available in
the standard repos. This is a Bad Thing and, I might add, a bug in the
SLE-12-SP3 Vagrant Box. It also makes install-deps.sh fail. Work around
the bug by reverting these four packages to the latest version that is
in the repos.
Fixes: https://github.com/SUSE/sesdev/issues/242
> provision.sh: reinstall certain packages from the update repos

- sesdev/__init__.py
- seslib/__init__.py
- seslib/exceptions.py
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
- tests/test_sesdev_parse_roles.py
ceph_salt_deployment.sh should not ask ceph-salt to provision:
- nodes with no roles at all
- nodes that have the "client" role and *only* the "client" role
because these nodes might be used later for QA testing.
---
seslib: refuse to process unknown roles
Also implement Node class helper methods "has_roles" and
"has_exclusive_role".
---
sesdev/_parse_roles: handle node with no roles
Fixes: https://github.com/SUSE/sesdev/issues/245
---
tests/test_sesdev_parse_roles.py: unit tests for _parse_roles
> ceph_salt_deployment: do not provision client-only nodes

- sesdev/__init__.py
- tests/test_is_a_glob.py
The idea behind this commit is that commands like "sesdev stop" should
do something reasonable if called like this:
sesdev stop '*'
Fixes: https://github.com/SUSE/sesdev/issues/193
> Stop, start, and destroy globbing

- README.md
- contrib/standalone.sh
- qa/common/common.sh
- qa/common/helper.sh
- qa/common/json.sh
- qa/common/zypper.sh
- qa/health-ok.sh
- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
- seslib/templates/deepsea/nautilus_policy.cfg.j2
- seslib/templates/deepsea/ses5_policy.cfg.j2
- seslib/templates/qa_test.sh
Until now, MDSs were not deployed in ses7, octopus, pacific, even if the
user specified one or more "mds" roles.
Fixes: https://github.com/SUSE/sesdev/issues/250
---
Rename "ganesha" role to "nfs"
"ceph -s" calls it "nfs", so we should, too.
---
qa: counting of nodes, daemons, services
With three different major versions of Ceph to support, and different
ways of counting in each one, this is a somewhat complicated
work-in-progress.
Also, take this opportunity to make the qa/ code shellcheck [1]-clean.
[1] https://github.com/koalaman/shellcheck
> ses7, octopus, pacific: Deploy MDSs

- seslib/__init__.py
When appropriate, we should add these roles instead of aborting with an
error message.
Fixes: https://github.com/SUSE/sesdev/issues/253
> Deployment: silently add "master" and "bootstrap" roles

- README.md
- contrib/standalone.sh
- sesdev/__init__.py
- seslib/__init__.py
- seslib/exceptions.py
- seslib/templates/caasp/provision.sh.j2
- seslib/templates/makecheck/provision.sh.j2
- seslib/templates/provision.sh.j2
When the command is issued, sesdev will create and provision a single
VM, and inside that VM it will create an ordinary user and grant it
passwordless sudo privileges. That user will then clone the git repo,
check out the branch, and run install-deps.sh and run-make-check.sh
inside it.
Originally, this feature was envisioned as "sesdev make-check VERSION",
but during the course of implementation the following was found to be
more expedient:
sesdev create makecheck \
--os leap-15.2 \
--ceph-repo https://github.com/ceph/ceph \
--ceph-branch octopus
(The main reason is that "make check" is tied more to operating system
than to SES version.)
Fixes: https://github.com/SUSE/sesdev/issues/82
> Implement feature "sesdev create makecheck"

- qa/README.rst
- qa/common/common.sh
- qa/health-ok.sh
- qa/shellcheck.sh
Since cephadm/orchestrator does Day 1 operations asynchronously, when an
Octopus/Pacific cluster is coming up it can take some time for the MDS
metadata to be updated. And, in fact, there is no guarantee that the MDS
metadata will be present before "ceph orch ls --service-type mds" starts
reporting the MDS as "running".
Also, do some general clean up of the qa bash scripting, including further
work to make it ShellCheck-clean and facilitate running ShellCheck on the
code.
> qa: fix maybe_wait_for_mdss test

- sesdev/__init__.py
- setup.cfg
openSUSE Leap 15.1 and SLE-15-SP1 are still on Click 6.7, so we have to
continue supporting it.
Fixes: https://github.com/SUSE/sesdev/issues/266
> sesdev: support Click 6.7

- sesdev/__init__.py
The new PrettyTable-based "sesdev list" output has some glitches. The
name of the first column should be "ID", instead of
"Deployments". And PrettyTable defaults to center alignment, which looks
bad.
> sesdev: tweak PrettyTable-based deployment list

- seslib/__init__.py
Before this fix, we might skip Stage 4 even though the "openattic" role
is given. In such a case, openATTIC would not get deployed, which is
a bug.
> deepsea: "openattic" role needs Stage 4

- README.md
- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
- seslib/templates/deepsea/deepsea_deployment.sh.j2
With this patch, when we want "salt ... state.apply" (SES7) or "salt-run
state.orch ..." (SES6, SES5), we simply give the option --salt. This is
much more straightforward (and easier to remember) than the previous
method.
Note: this patch does *not* change the default behavior, which is to use
"ceph-salt deploy --non-interactive" (SES7) or "deepsea stage run ..."
(SES6, SES5). The patch only renames the options used to trigger the
non-default behavior.
> Rename --deepsea-cli and --ceph-salt-deploy options to --salt

- contrib/standalone.sh
- sesdev/__init__.py
- seslib/__init__.py
We assume that "master" will be an "admin" node, and hence that
"ceph mgr services" will work there.
This commit changes the logic so the output of "ceph mgr services" is
parsed in the Python code, instead of by piping the output to "jq" and
"sed" on the cluster node like we were doing before.
It also adds a regression test for the dashboard tunnelling feature,
which also asserts that at least *some* form of dashboard downstream
branding has been applied in SES5, SES6 and SES7.
Also take the opportunity to make "contrib/standalone.sh"
ShellCheck-clean.
Fixes: https://github.com/SUSE/sesdev/issues/269
> seslib: more robust dashboard tunnelling

- README.md
We currently have two "build: passing" icons right next to each other,
like this:
build | passing    build | passing
Without context, this looks like a mistake. Also, readers might be
interested in what these icons mean.
> README.md: give some context for the "build: passing" icons

- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Since https://github.com/ceph/ceph-salt/pull/184, it's no longer possible to to disable cephadm bootstrap in `ceph-salt`.
---
~~After https://github.com/ceph/ceph-salt/pull/184~~
~~After https://github.com/SUSE/sesdev/pull/258~~
> Remove "disable cephadm bootstrap" functionality

- seslib/__init__.py
The linter started complaining that log_handler was not being used in
the "stop" routine, so let's start using it to make the linter happy.
> seslib: fix "Unused argument" linter warning

- contrib/standalone.sh
The "JavaScript required" page of the SES7 Dashboard is missing
SUSE branding.
Works-around: https://bugzilla.suse.com/show_bug.cgi?id=1170498
> contrib/standalone.sh: do not fail because of bsc#1170498

- seslib/templates/caasp/loadbalancer.sh.j2
- seslib/templates/caasp/master.sh.j2
- seslib/templates/caasp/provision.sh.j2
- seslib/templates/caasp/storage.sh.j2
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
- seslib/templates/deepsea/deepsea_deployment.sh.j2
- seslib/templates/deepsea/ses5_pre_stage_0.sh.j2
- seslib/templates/provision.sh.j2
- seslib/templates/suma/suma_deployment.sh.j2
We transiently hit the following error when running "zypper install",
even when network connectivity is OK:
Media source
'http://download.opensuse.org/distribution/leap/15.2/repo/oss/' does not
contain the desired medium
This is because the SLE/Leap repos are periodically updated and we race
with these updates. To reduce the probability of hitting the error, we
enable "autorefresh" on all zypper repos.
Fixes: https://github.com/SUSE/sesdev/issues/287
> provision.sh: enable autorefresh on all repos

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
- seslib/templates/sync_clocks.sh.j2
Before, we had some very simplistic code for syncing the clocks with the
time server before deploying additional MONs. This code was not actually
syncing the clocks.
> ceph_salt_deployment: really sync clocks

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
ceph-salt got the ability to sync the clocks with
https://github.com/ceph/ceph-salt/pull/202
and that rendered this code superfluous.
> ceph_salt_deployment.sh: rip out time sync code

- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
`ceph-salt deploy` command was renamed to `ceph-salt apply`, so we should rename the `--stop-before-ceph-salt-deploy` option accordingly.
> Rename '--stop-before-ceph-salt-deploy' to '--stop-before-ceph-salt-apply'

- seslib/templates/deepsea/create_all_pools_at_once.sh.j2
- seslib/templates/deepsea/deepsea_deployment.sh.j2
- seslib/templates/provision.sh.j2
Pre-create CephFS and iSCSI Gateway pools with a number of PGs calculated to
avoid health warnings.
See also https://github.com/SUSE/DeepSea/issues/536
Fixes: https://github.com/SUSE/sesdev/issues/294
> deepsea_deployment: pre-create Stage 4 pools

- seslib/templates/caasp/master.sh.j2
This is a fix for https://github.com/SUSE/sesdev/issues/299
As @smithfarm removed the multi-master deployment functionality from sesdev (caasp part) this is a quick fix to get the caasp deployment up and running again. If we ever need the possibility to do multi-master with caasp we could add it back. 
Signed-off-by: Kai Wagner <kwagner@suse.com>
> caasp master provision fix

- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
This PR adds a new `--stop-before-ceph-orch-apply` option that allows to stop the deployment before applying ceph orch service spec (before deploying ODS, MON, MGR, etc..).
This option replacing the old `--deploy-mons`, `--deploy-mgrs`, `--deploy-osds` and `--deploy-mdss` options.
> Add '--stop-before-ceph-orch-apply' option

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Forgot to remove one occurrence of `ceph_salt_deploy_osds` in https://github.com/SUSE/sesdev/pull/301
> Option '--deploy-osds' no longer exists

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
ed870ab4f7838200729dabc93bce108ba9464aa3 got rid of
"ceph_salt_deploy_mdss" but we still need to check that there are some "mds"
roles present and, if not, refrain from issuing the command
ceph fs volume create myfs ...
Fixes: ed870ab4f7838200729dabc93bce108ba9464aa3
> ceph_salt_deployment: do not deploy MDS if no mds roles present

- seslib/templates/provision.sh.j2
Like "which", "curl" is an RPM that is often silently assumed to be
present, leading to bugs like:
https://tracker.ceph.com/issues/44498
> provision.sh: remove curl RPM from the environment

- seslib/templates/makecheck/provision.sh.j2
Compiling Ceph requires a number of "libfoo-devel" RPMs. These are typically
shipped in a different SLE Module than their corresponding library RPMs.
Sometimes, an update to the library RPM ("libfoo1") reaches the IBS Vagrant Box
before the corresponding update to the "libfoo-devel" package reaches the
IBS repos. This state, which can last for days or even weeks, typically causes
install-deps.sh to fail on a zypper conflict.
Possibly prophylactically downgrade libraries known to have caused this
problem in the past.
> makecheck: possibly prophylactically downgrade problem packages

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Adapts `sesdev` according to https://github.com/ceph/ceph-salt/pull/235
> Make use of 'cephadm' role

- contrib/standalone.sh
From time to time, various deployment types and configurations can
become unreliable, making it very difficult to get through an entire
"contrib/standalone.sh --full" run even when there are no bugs in the
sesdev branch under test.
Since "contrib/standalone.sh --full" typically runs over night, it can
be very inconvenient when issues unrelated to sesdev cause the script to
abort. This commit provides a "--no-stop-on-failure" option for times
when we want the script to run to completion, regardless of failures.
> contrib/standalone.sh: --no-stop-on-failure option

- seslib/__init__.py
- seslib/templates/provision.sh.j2
As far as I can tell, Salt is not required in a CaaSP deployment.
> caasp: do not install salt

- contrib/standalone.sh
- seslib/__init__.py
- seslib/exceptions.py
Recently, supportconfig started creating tarballs starting with "scc",
whereas before they used to start with "nts". Handle both cases.
Fixes: https://github.com/SUSE/sesdev/issues/322
> supportconfig: handle /var/log/scc* and /var/log/nts*

- qa/common/common.sh
cephadm creates (and co-locates) a fourth MGR (even when we ask for only
three) often enough for the false negatives it causes in sesdev
regression testing to be an annoyance.
Works-around: https://tracker.ceph.com/issues/45093
> qa: work around cephadm MGR co-location issue

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Since 73a121a81e28c4d9acefc5cf3bcaf907463d7fda the use_salt=True
(--salt) deployment has been broken.
When using Salt to apply the Salt Formula, one must sync the Salt
modules (i.e. copy the modules to all the minions) manually, first.
When using "ceph-salt apply", this step is automated.
Fixes: 73a121a81e28c4d9acefc5cf3bcaf907463d7fda
Fixes: https://github.com/ceph/ceph-salt/issues/198
> ceph_salt_deployment: fix use_salt=True deployment

- seslib/templates/makecheck/provision.sh.j2
Avoid the following zypper conflict:
```
03:20:45 Problem: ncurses-devel-6.1-lp152.7.53.x86_64 requires libncurses6 = 6.1-lp152.7.53, but this requirement cannot be provided
03:20:45   not installable providers: libncurses6-6.1-lp152.7.53.x86_64[oss]
03:20:45  Solution 1: Following actions will be done:
03:20:45   do not install ncurses-devel-6.1-lp152.7.53.x86_64
03:20:45   do not install cunit-devel-2.1.3-lp152.3.5.x86_64
03:20:45   do not install libxml2-devel-2.9.7-lp152.7.7.x86_64
03:20:45   do not install xmlsec1-devel-1.2.28-lp152.1.2.x86_64
03:20:45   do not install xmlsec1-openssl-devel-1.2.28-lp152.1.2.x86_64
03:20:45  Solution 2: downgrade of libncurses6-6.1-lp152.7.57.x86_64 to libncurses6-6.1-lp152.7.53.x86_64
03:20:45  Solution 3: break ncurses-devel-6.1-lp152.7.53.x86_64 by …
```
> makecheck: possibly prophylactically downgrade libncurses6

- qa/common/common.sh
We already added this workaround for
https://tracker.ceph.com/issues/45093 to
number_of_daemons_expected_vs_metadata_test, but it's needed in
number_of_nodes_actual_vs_expected_test as well.
> qa: tolerate +1 MGRs in number_of_nodes_actual_vs_expected_test

- README.md
- sesdev/__init__.py
- seslib/__init__.py
This PR adds the `replace-ceph-salt` command that allows the user to re-install ceph-salt from a given source (by using `rsync` to update files):
```
```
This PR was inspired by https://github.com/SUSE/sesdev/pull/24, so all different options to fetch code should be consistent between both `replace-ceph-salt` and `replace-mgr-modules` commands.
For now, only `local` code is supported.
> Allow user to re-install ceph-salt from source

- seslib/__init__.py
- seslib/exceptions.py
The "admin" role must continue to exist because previous versions of
sesdev used it (so existing deployments might be using it, and we still
want to be able to list them, destroy them, ssh to them, etc.). But we
don't want folks using it in new deployments.
Fixes: https://github.com/SUSE/sesdev/issues/329
> seslib: no longer allow explicit "admin" role

- seslib/templates/sync_clocks.sh.j2
This commit refactors the script so it bails out properly when there is
a problem.
References: https://github.com/SUSE/sesdev/issues/327
> sync_clocks.sh: put chronyc calls in try_wait

- sesdev/__init__.py
- seslib/__init__.py
This option was implemented at a time when it was not certain whether
SES7 would use cephadm or deepsea as its deployment tool.
> Drop the --use-deepsea option for {ses7,octopus,pacific}

- contrib/standalone.sh
- sesdev/__init__.py
- seslib/__init__.py
- seslib/exceptions.py
- tests/test_vet_dep_id.py
It's not a good idea to allow users to specify a deployment ID that
would not be a valid hostname element [1], since the deployment ID
might be used as a hostname element.
[1] from hostname(7) - Linux manual page:
Each element of the hostname must be from 1 to 63 characters long and the
entire hostname, including the dots, can be at most 253 characters long.
Valid characters for hostnames are ASCII(7) letters from a to z, the digits
from 0 to 9, and the hyphen (-).
> Deployment: vet deployment ID before creation

- qa/common/common.sh
- qa/common/json.sh
- qa/health-ok.sh
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Until now, we were ignoring the "nfs" (Ganesha) role. With this
commit, we at least start the NFS daemon using the documented
procedure and, in qa-test, assert (with "ceph orch ls") that it is
running.
Fixes: https://github.com/SUSE/sesdev/issues/256
> ses7,octopus,pacific: deploy NFS-Ganesha

- qa/common/helper.sh
- qa/health-ok.sh
- seslib/__init__.py
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
We have some messy code in ceph_salt_deployment.sh which populates some shell variables with the names of nodes that are supposed to have a given role.
This changeset moves this code into `seslib/__init__.py` by populating python arrays with the same information and converting these into comma-separated strings which are sent into ceph_salt_deployment.sh via the Jinja context.
This also lays some groundwork for further PRs expanding the QA tests so they not only vet the expected number of daemons of various types, but also assert that daemons are actually running on the expected nodes.
> cleanup: nodes_with_role

- qa/common/common.sh
- qa/common/rgw.sh
- qa/common/zypper.sh
- qa/health-ok.sh
- seslib/templates/qa_test.sh.j2
For all nodes that are expected to have an RGW running, use "curl" to
send an "http(s)" request to the RGW port on the node. If an RGW really
is listening on the port, it will send back a response, the body of
which will contain valid XML.
Exploit this RGW behavior to implement a smoke test.
Fixes: https://github.com/SUSE/sesdev/issues/343
> qa: implement rgw smoke test

- CHANGELOG.md
- sesdev/__init__.py
- seslib/__init__.py
If not provided explicitly via the `--domain` option, new deployments now default to `.test` instead of `.com` as the cluster TLD.
Fixes: https://github.com/SUSE/sesdev/issues/348
Signed-off-by: Lenz Grimmer <lgrimmer@suse.com>
> Default to ".test" instead of ".com" for the cluster TLD

- seslib/__init__.py
- seslib/exceptions.py
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
CAVEAT: THIS NEEDS https://github.com/ceph/ceph/pull/33954 and https://github.com/ceph/ceph/pull/34860 - OTHERWISE IT DOESN'T WORK!
---
YAML is nicer than JSON
---
To Do:
> ceph_salt_deployment: deploy OSDs from YAML (ServiceSpec) file

- qa/common/common.sh
- qa/common/helper.sh
- qa/common/rgw.sh
- qa/health-ok.sh
- seslib/__init__.py
- seslib/templates/cluster_json.sh.j2
- seslib/templates/provision.sh.j2
- seslib/templates/qa_test.sh.j2
Our systemctl test will use ssh to run a script on each node.
The script will need to know (or be able to look up) certain
characteristics of the cluster configuration.
With this commit, a file (/home/vagrant/cluster.json) is created
on each node. The cluster.json file contains a data structure
into which we place all the information needed by tests that
health-ok.sh triggers on an arbitrary node.
Fixes: https://github.com/SUSE/sesdev/issues/342
> qa: compare systemctl with expected state on each node

- seslib/__init__.py
If there's no containers running on a node, then `replace-mgr-modules` is failing because:
```
>>> 'a\nb\n'.strip().split('\n')
['a', 'b']
>>> '\n'.strip().split('\n')
['']
```
> Fix "replace-mgr-modules" when no containers are running on node

- README.md
- contrib/standalone.sh
- sesdev/__init__.py
- seslib/__init__.py
- seslib/exceptions.py
- seslib/templates/Vagrantfile.j2
- seslib/templates/provision.sh.j2
The --devel/--product option (default: --devel) controls whether the
"devel" repo will be added to the nodes prior to deployment.
For SES{5,6,7}, the "devel" repo is Devel:Storage:{5,6,7}.0 Media1.
For {nautilus,octopus,pacific}, the "devel" repo is something like
"filesystems:ceph:...". For other create targets, the "devel" repo is
undefined and this PR is a noop.
This commit also implements an "add-repo" subcommand which can be used
to add either the "devel" repo or an arbitrary, "custom" repo to an
already-running cluster, and optionally update the cluster to newer (or
older) versions of packages contained in that repo at the same time.
---
> Add --devel/--product option and add-repo subcommand

- seslib/__init__.py
Since Tumbleweed is now on Octopus, nautilus is not expected to be built
for Factory/Tumbleweed anymore in filesystems:ceph:nautilus.
Also, the "octopus" deployment target is expected to deploy something
very similar, if not identical, to SES7 on openSUSE Leap 15.2. So use
`filesystems:ceph:octopus` by default, instead of
`filesystems:ceph:octopus:upstream`.
> seslib: no longer support nautilus deployment in Tumbleweed

- qa/common/rgw.sh
In an SES5 single-node cluster, openattic and rgw are running on the
same node. In that case, DeepSea sets the RGW port to 8080 instead of
80. There might be other cases where the deployment tooling sets
a different port.
Make the RGW smoke test handle these cases better. It still only looks
in /etc/ceph/ceph.conf (not in the MON config store), but it's an
incremental improvement.
> qa/rgw: get RGW port from /etc/ceph/ceph.conf

- Jenkinsfile.integration
- README.md
sesdev can be installed and used on SUSE Linux Enterprise just as well as on openSUSE. The README should make that clear.
Also, it's not necessary to explicitly write "sudo" everywhere.  Users are expected to be savvy enough to know what "run as root" means.
Finally, AFAICT `bridge-utils` is not needed to run sesdev (it contains a single executable - brctl - which has been obsoleted by `iproute2`), so drop all mentions of it.
Fixes: 8dcf52429dfd4a67b1dda19984b33d490f179f61
> README.md: sesdev can be installed on SLE, too, and bridge-utils is not needed

- seslib/templates/provision.sh.j2
A misuse of Jinja syntax crept in.
Fixes: f4ae4a041650f3ca113363d4ad7fd66d6760555c
> provision.sh: fix regression

- seslib/templates/provision.sh.j2
We were setting up SSH keys **after** running zypper, which was a recipe
for disaster.
Fixes: https://github.com/SUSE/sesdev/issues/360
> provision.sh: set up SSH keys earlier

- contrib/standalone.sh
- qa/common/common.sh
- qa/common/helper.sh
- qa/health-ok.sh
- sesdev/__init__.py
- seslib/__init__.py
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
- seslib/templates/deepsea/deepsea_deployment.sh.j2
- seslib/templates/qa_test.sh.j2
Though FileStore is not supported in SES7, the ability to deploy
FileStore OSDs is still present in Octopus and Pacific, even though it
is currently broken there.
Implement a --filestore option which adds the appropriate line to the
drive groups file (ses6,nautilus)/service spec file
(ses7,octopus,pacific) before deploying the OSDs.
Also, add a qa test asserting that the OSD metadata reports the expected
objectstore.
Fixes: https://github.com/SUSE/sesdev/issues/340
---
To Do:
> Implement --filestore option to deploy OSDs with FileStore

- contrib/standalone.sh
- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
- seslib/templates/qa_test.sh.j2
Instead of calling "ceph orch apply <service>" for each type of daemon
we want to deploy,
1. make a big service spec yaml blob for {mon,mgr,osd,mds} and run
"ceph orch apply" on it
2. wait for all the OSDs to join the cluster
3. make a second big service spec yaml blob for {rgw,nfs} (and others to
be added later) and run "ceph orch apply" on it
The rationale for this is:
1. this is more idiomatic for cephadm, and
2. it brings us closer to the goal of generating one, big blob of YAML for the whole cluster to be passed to "cephadm bootstrap" via "ceph-salt config/apply".
> ceph_salt_deployment.sh: reduce number of "ceph orch apply" calls

- seslib/templates/engine/libvirt/vagrant.node.j2
- seslib/templates/provision.sh.j2
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
Fixes: https://github.com/SUSE/sesdev/issues/181
Not sure why we only set the name as the hostname when we have the fqdn. Alos can't hurt to set the minion id explicitly.
> provisioning: set fqdn through vagrant and leave /etc/hosts alone

- contrib/standalone.sh
- qa/common/common.sh
- qa/common/json.sh
I tried to deploy a cluster with no "mds" role, and QA test failed:
master: 0 MDS daemons did not appear even after waiting 5 minutes.
Giving up.
This is because we were running the test whenever "$expected_mdss" is
non-empty, which is the wrong conditional criterion, since it's always
going to be true (the string "0" is non-empty).
Fixes: https://github.com/SUSE/sesdev/issues/366
> qa: do not wait for non-existent daemons to start

- qa/common/rgw.sh
- qa/health-ok.sh
When this test is run very soon after Day 1 cluster deployment
completes, the RGW might not be ready to respond to requests
when the curl command is issued.
Fixes: https://github.com/SUSE/sesdev/issues/369
> qa/rgw: run curl command in try-wait loop to ping RGW

- qa/common/common.sh
- qa/health-ok.sh
- seslib/templates/cluster_json.sh.j2
Until now, we have not been testing whether the desired number of iSCSI
Gateways (IGWs) was actually deployed.
Now that we have IGW deployment in {octopus,ses7,pacific}, it's time to
add this code.
> qa: add IGW to existing tests

- seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
This PR adds iSCSI support on ceph-salt deployments (>= octopus).
---
To Do (or Consider Doing) Before DNM Can Be Removed:
> cephadm iSCSI deployment

- sesdev/__init__.py
As a result of cf327719fcc5d76ea0d54db0a99342b6c1dfdfd3 we can no longer
use characters like "_" (underscore) and "." (fullstop) in deployment
IDs. Because "makecheck" generates the deployment ID from the OS ID
which might contain these characters, we sanitize it by converting these
characters to "-" (hyphen).
Fixes: cf327719fcc5d76ea0d54db0a99342b6c1dfdfd3
> sesdev: sanitize makecheck deployment IDs

- contrib/standalone.sh
- sesdev/__init__.py
- seslib/__init__.py
Before this patch, one had to explicitly give "--ceph-repo" and
"--ceph-branch" options on the "sesdev create makecheck" command line if
one wanted to run make check on anything other than the upstream branch.
We can do better than that.
---
> makecheck: reasonable defaults for Ceph repo/branch

- seslib/templates/cluster_json.sh.j2
If systemctl_test.sh is run manually, the human running it might forget
that it needs a Ceph Cluster FSID on {octopus,ses6,pacific}. Produce a
helpful error message in that case.
---
To Do:
> qa/systemctl_test: better error message when FSID omitted

- qa/common/common.sh
- qa/health-ok.sh
Only for VERSION_ID="15.1" for the time being. VERSION_ID="15.2" support
is blocked by https://bugzilla.suse.com/show_bug.cgi?id=1170498 and
the test for VERSION_ID="12.3" would need different semantics
(openATTIC).
References: https://github.com/SUSE/sesdev/issues/292
> qa: implement superficial test for presence of dashboard branding

- sesdev/__init__.py
Valid characters for hostnames are ASCII(7) letters from a to z, the digits from 0 to 9, and the hyphen (-).
Signed-off-by: supriti <supriti.singh@suse.com>
> Update the example Deployment id in sesdev help

- sesdev/__init__.py
- seslib/exceptions.py
Since --single-node silently clobbers --roles, it's not a good
idea to let the user set them both at the same time.
Fixes: https://github.com/SUSE/sesdev/issues/304
> sesdev: raise exception if --roles combined with --single-node

- seslib/constant.py
Fix the error `The DeepSea version used in SES5 does not recognize 'prometheus' or 'grafana' as roles in policy.cfg.` when creating a cluster with default roles.
> sesdev: use Luminous roles for SES5

- contrib/standalone.sh
- sesdev/__init__.py
- seslib/settings.py
"sesdev create" with the `--dry-run` option implemented by this commit
will bail out before creating any VMs.
In practice, this means immediately prior to triggering `Deployment.start()`
Useful for testing.
> sesdev: implement --dry-run for create commands

- qa/common/common.sh
Now that nfs-ganesha has been updated to 3.3 on SES7 as well
as filesystems:ceph:octopus, we can run the full set of NFS smoke tests
on ses7 as well as octopus.
> qa/nfs: run all nfs smoke tests on ses7 as well as octopus

- qa/common/common.sh
- seslib/templates/salt/cluster_json.j2
Now that https://build.suse.de/request/show/221714 has been accepted,
it should now be possible to test for presence of dashboard branding
in octopus (filesystems:ceph:octopus) and ses7 (but not "pacific").
> qa: enable dashboard branding test on {octopus,ses7}

- seslib/deployment.py
This commit improves the "deployment status and parameters" listing
by restructuring it.
Many of the parameters that were being displayed for each node
separately are actually parameters of the deployment as a whole,
so it didn't make sense to display them for each node separately.
> deployment/status: aggregate global parameters

- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
master: OSDs in cluster (actual/expected): 0/4 (try 49 of 50)
master: OSDs in cluster (actual/expected): 0/4 (try 50 of 50)
master: OSDs in cluster (actual/expected): 0/4 (try 51 of 50)
Oops!
> ceph_salt_deployment: fix off-by-one error in OSDs wait loop

- contrib/standalone.sh
- sesdev/__init__.py
- seslib/settings.py
After some recent refactoring, the following command was being
handled non-interactively:
sesdev create octopus --qa-test
Which is obviously wrong and must be fixed.
Fixes: 88511aac72e0ecfbcd6af247f49c99ec8f4876b0
> sesdev: fix --non-interactive/--force handling

- seslib/templates/zypper.j2
Pre-installed packages in the Vagrant Box can hide bugs (an undeclared 
dependency being a bug).
> zypper: remove rsync if it's installed in the Vagrant Box

- README.md
- sesdev/__init__.py
This means that, by default, no repos will get elevated zypper priority.
If users providing custom repos on the "sesdev create" command line
want those repos to get elevated priority, they will need to explicitly
provide the "--repo-priority" option.
Rationale:
An important use case for custom repos in sesdev is for troubleshooting
version numbering issues on maintenance updates. If we set zypper
priorities on the custom repos by default, the engineer working on the
version numbering issue might be taken by surprise.
Since zypper itself does not *default* to setting an elevated priority,
it seems odd for sesdev to be doing that.
One problem with this approach is that Ceph packages built directly from
upstream repos might get a version number that is _lower_ than the ceph
RPM version in …
> Change --repo-priority default from "True" to "False"

- seslib/deployment.py
This fixes a hang that can happen on "sesdev list" and other commands
that list existing deployments.
> deployment: generate static networks on create only

- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
We might see clusters fail to deploy because OSDs fail to
come up:
...
master: OSDs in cluster (actual/expected): 0/4 (try 47 of 50)
master: OSDs in cluster (actual/expected): 0/4 (try 48 of 50)
master: OSDs in cluster (actual/expected): 0/4 (try 49 of 50)
master: OSDs in cluster (actual/expected): 0/4 (try 50 of 50)
master: It seems unlikely that this cluster will ever reach the expected number of OSDs. Bailing out!
In that case, issue a "ceph status" command so the log shows the high-level
state of the cluster when this happens.
> ceph_salt_deployment: "ceph -s" when OSDs fail to come up

- seslib/templates/salt/deepsea/ses5_pre_stage_0.sh.j2
This partially reverts f1fb650b2309e9f91098da02bff795238e6d95a2
which was monkey-patching srv/salt/ceph/time/ntp/default.sls to work
around a bug in the Salt that affects SES5. (That bug was preventing
sesdev from syncing the clocks.) In the meantime the following
commit:
https://github.com/SUSE/DeepSea/pull/1823/commits/d22232629d7d55387b7d6eaee7a510eced848d34
was merged into the SES5 DeepSea branch and started shipping to
customers, so the monkey-patch no longer applies cleanly (and is
no longer needed).
> ses5: stop patching srv/salt/ceph/time/ntp/default.sls

- README.md
- sesdev/__init__.py
- seslib/constant.py
- seslib/deployment.py
- seslib/exceptions.py
- seslib/node.py
- seslib/settings.py
- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
- seslib/templates/zypper.j2
- seslib/tools.py
- seslib/zypper.py
The way we were handling the "custom repo" (repo specified by the
user on the command line) was suboptimal.
---
> seslib: revamp custom_repo

- README.md
- seslib/deployment.py
Vagrant knows how to destroy the whole cluster with a single command,
so try that first. If that fails, fall back to destroying each
node individually like we were doing before, except ignore errors.
This fixes the issue where a cluster that is expected to have nodes:
"master", "node1", "node2", and "node3" but in reality only has
two nodes "node2" and "node3" cannot be destroyed because sesdev
first tries to destroy "master" but this fails, causing sesdev to bail
out.
---
> seslib/deployment: try to destroy the whole cluster at once

- seslib/templates/provision.sh.j2
This ensures that journal (log) messages are not lost unnecessarily.
For a rationale, see https://github.com/ceph/ceph-salt/issues/304
> provision.sh: persist the journal

- seslib/deployment.py
Otherwise, it might run forever (or until the sesdev user hits CTRL-C,
or until the libvirtd machine powers down).
> deployment: run supportconfig with 1-hour timeout

- contrib/standalone.sh
- sesdev/__init__.py
- seslib/constant.py
- seslib/exceptions.py
- seslib/log.py
Until now, the only way to see the log messages was with "--log-file".
Having the ability to show log messages on the screen can help
with troubleshooting.
---
> log: print log messages to the screen under certain circumstances

- README.md
- contrib/standalone.sh
- seslib/constant.py
- seslib/deployment.py
- seslib/settings.py
I never liked "version_os_repo_mapping". In our SES team parlance,
these repos are collectively referred to as "devel repos", so
the name will be more descriptive, and less confusing, if we include
the term "devel repos" in it.
Of course, it's a bit of a long-shot to say that the team is used to
referring to, e.g., "filesystems:ceph:nautilus" as the "SES6 devel repo
for OBS", but that's effectively what it is. (The OBS equivalent
of the SES6 product repo is the Leap 15.1 base repo.)
> Change "version_os_repo_mapping" to "version_devel_repos"

- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Also change how the progress towards timeout expiration is reported in
the log, to give log readers an idea of how much time elapsed.
References: https://github.com/SUSE/sesdev/issues/412
> ceph_salt_deployment.sh: extend OSD timeout

- sesdev/__init__.py
- seslib/constant.py
- seslib/deployment.py
- seslib/node.py
- seslib/settings.py
Over time, a diverse range of role-related constants got added to the
code base. This commit unifies them so they all start with ROLES_
> Unify role-related constants

- contrib/standalone.sh
- seslib/settings.py
A user reported the following Traceback:
```
Traceback (most recent call last):
File "/run/media/rimarques/data/projects/sesdev/venv/bin/sesdev", line 11, in <module>
load_entry_point('sesdev', 'console_scripts', 'sesdev')()
File "/run/media/rimarques/data/projects/sesdev/sesdev/__init__.py", line 38, in sesdev_main
cli(prog_name='sesdev')
File "/run/media/rimarques/data/projects/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "/run/media/rimarques/data/projects/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "/run/media/rimarques/data/projects/sesdev/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
return …
```
> settings: rename straggler version_os_repo_mappings

- README.md
- seslib/templates/caasp/master.sh.j2
"loadbalancer" role could be deployed on master, so don't need for Rook testing especially if there are not much resources to waste on it.
Updated docs to clarify CaaSP option a little.
> remove hard dependency on loadbalancer and update doc for CaaSP

- setup.cfg
The "options.package_data" file list in setup.cfg determines which
template files get included in the sesdev Python package and that,
in turn, determines which files and directories get included in the
RPM package.
Commit 53c782290650ba57eff009c5dcc08d4d540a20a1 refactored the template
files but forgot to update setup.cfg accordingly.
Fixes: 53c782290650ba57eff009c5dcc08d4d540a20a1
> setup.cfg: fix "options.package_data" file list

- seslib/deployment.py
- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
If we hit https://tracker.ceph.com/issues/46990, mgr/cephadm enters
a 600 second timeout before it resets the SSH connection, and in
that case 900 seconds is not enough for cephadm to finish deploying
the OSDs.
> ceph_salt_deployment: extend OSD deployment timeout

- README.md
- sesdev/__init__.py
- seslib/constant.py
- seslib/deployment.py
- seslib/templates/caasp/master.sh.j2
Before this commit, we were setting num_disks default for
sesdev create caasp4 --deploy-ses
in a different way than for standard Ceph deployments. As a result, we
were only getting 2 disks even on a single-node caasp4 deployment.
> caasp: set num_disks in same way as for ceph deployments

- README.md
- seslib/deployment.py
- seslib/exceptions.py
- seslib/templates/caasp/master.sh.j2
This PR is a mixed bag of `caasp4` cleanups and fixes:
1. caasp4 clusters must not have more than one role per machine, which might not be clear to all users
2. the regex for counting worker nodes would only work up to 10 worker nodes, but there's no reason why it couldn't handle more
3. finally, I found that we were adding disks even when the user doesn't need them - add a commit to address that
> vet_configuration: vet caasp4 roles more carefully

- sesdev/__init__.py
- seslib/constant.py
- seslib/templates/caasp/master.sh.j2
- seslib/templates/caasp/provision.sh.j2
Update repos and image for CaaSP deployment to SLE15 SP2.
There still a need for Pub Cloud SP1 repo for one dependency (CaaSP
would fix it later).
Signed-off-by: Denis Kondratenko <denis.kondratenko@suse.com>
> caasp: update to caasp 4.5

- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Before this commit, the only way to prepare a cluster for manual Day
2 deployment would be to pass the `--stop-before-ceph-orch-apply`
option. But it seems weird to be forced to assign fictional roles just
to get a cluster with X nodes that has just been bootstrapped.
With this commit, machines with no roles at all [1] will still get added
to the cluster. Later, the user can SSH into the cluster and use these
machines in manual Day 2 deployment operations.
[1] For example: `--roles="[master],[mon,mgr,bootstrap],[],[],[]"`
> cephadm: allow preparation of cluster for manual deployment

- seslib/templates/salt/deepsea/nautilus_policy.cfg.j2
- seslib/templates/salt/deepsea/ses5_policy.cfg.j2
One fine day, we noticed that sesdev was not adding ganesha roles to
policy.cfg in {ses5,nautilus,ses6} clusters.
> deepsea: add ganesha roles to policy.cfg

- seslib/deployment.py
When users specify no "storage" roles, but explicitly give the
--num-disks option, assume they intend to deploy OSDs manually.
In such a case, they will expect to have the attached disks on
all nodes except, perhaps, a standalone master node (if any).
---
To Do:
> deployment: disks even when explicit storage role not given

- seslib/deployment.py
The _generate_nodes() method had a bunch of code that didn't belong
there. Moved it into separate "helper" methods that are called from the
constructor.
> cleanup: move code out of Deployment/_generate_nodes()

- .travis.yml
- sesdev/__init__.py
- seslib/box.py
- seslib/constant.py
- seslib/deployment.py
- seslib/exceptions.py
- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
- setup.cfg
- setup.py
- tests/test_is_a_glob.py
- tests/test_pytest_smoke.py
- tests/test_sesdev_parse_roles.py
- tests/test_vet_dep_id.py
- tox.ini
This patchset
- streamlines the project's overall unit testing and code linting (tox/pytest/pylint/pycodestyle)
- runs the tests against Python 3.8 instead of 3.7
- runs pycodestyle from within pytest, instead of having it has a separate step
> cleanup: streamline unit testing and code linting

- seslib/deployment.py
We are already ensuring that Python 2 will not be present in the system,
so installing "python2-pip" here will actually pull in the entire Python
2 stack. Also, Python 2 is only available in SLE-15-SP2 via the "Python
Legacy" module which sesdev does not add to the deployment.
Fixes: https://github.com/SUSE/sesdev/issues/430
> replace-mgr-modules: refrain from introducing Python 2

- contrib/standalone.sh
- qa/common/common.sh
- qa/common/helper.sh
- qa/health-ok.sh
- seslib/constant.py
- seslib/deployment.py
- seslib/exceptions.py
- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
- tox.ini
The documentation states that the only node that **must** have an
"admin" role is the bootstrap node. On all other nodes, including the
master node, "admin" is optional.
I realized that our previous approach, which was to apply the "admin"
role to all nodes without exception, might not be ideal for realistic
testing. According to the SES7 manual, this configuration is not
recommended.
So, this commit makes it possible for the user to specify which nodes
get the "admin" role when deploying {octopus,ses7,pacific} clusters, 
with the caveat that then "admin" role must be given on nodes that 
have the "bootstrap" and/or the "master" role. (On the "master" node,
"admin" is not strictly required, but it seems safe to assume that most
real-life deployments will have it, since it's natural to …
> ceph-salt: enable user to control which nodes get "admin" role

- seslib/deployment.py
https://github.com/ceph/ceph-salt/pull/329 will introduce `ceph-salt` runners, so `sesdev replace-ceph-salt` should be adapted to also sync runners.
> replace-ceph-salt should also sync salt runners

- sesdev/__init__.py
- seslib/deployment.py
- seslib/settings.py
- seslib/templates/provision.sh.j2
This commit adds support for simulating mixed SSD/HDD clusters. For the
time being, we keep it simple:
1. if --ssd is not given, all disks are rotational (as before)
2. if --ssd is given, the first additional disk on each node is set to
"non-rotational", thereby simulating an SSD
In other words, this commit does not add support for complicated
configurations like
1. multiple SSDs per node
2. clusters where disk HW configurations vary from node to node
Fixes: https://github.com/SUSE/sesdev/issues/37
> If --ssd option is given, make first additional disk non-rotational

- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
cephadm is known to transiently deploy two MONs/MGRs on a node, even
when only one was asked for. Let the deployment continue when this
happens at bootstrap time.
References: https://tracker.ceph.com/issues/45093
> ceph_salt_deployment: tolerate additional bootstrap MONs/MGRs

- seslib/deployment.py
- seslib/templates/provision.sh.j2
Avoid the following error:
master:~ # ssh node1.ses7.test cephadm ls
The authenticity of host 'node1.ses7.test (10.20.144.201)' can't be established.
ECDSA key fingerprint is SHA256:G0eqcFcad9Kys0zcKl4mbncUd33rMc6DZroPTHNKwVg.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
Fixes: https://github.com/SUSE/sesdev/issues/454
> provision.sh: disable host checking when SSHing within the cluster

- seslib/templates/caasp/master.sh.j2
- seslib/templates/provision.sh.j2
- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
- seslib/templates/salt/cluster_json.j2
- seslib/templates/salt/deepsea/create_all_pools_at_once.sh.j2
- seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
- seslib/templates/salt/provision.sh.j2
- seslib/templates/salt/wait_for_minions.j2
- seslib/templates/zypper.j2
As of some recent version of Vagrant, it started removing the master
domain (i.e., destroying the master node) whenever the provisioning
script exits with a code other than "0".
Deleting the master node makes it impossible to investigate why the
script failed.
I can't think of any good reason for Vagrant/vagrant-libvirt to behave
like this. It's a recent development. I don't know how to turn the
behavior off, but I can at least work around it by preventing the
deployment script from returning any exit code other than 0.
> ceph_salt_deployment: prevent Vagrant from deleting master node

- seslib/templates/provision.sh.j2
- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Until this commit, the first ceph-salt command we executed was
ceph-salt config /ceph_cluster/minions add {{ node.fqdn }}
When that command fails, we don't really know whether it's a problem
with ceph-salt as a whole, or just the "ceph-salt config" component.
> ceph_salt_deployment: expose ceph-salt errors early

- qa/common/common.sh
- qa/common/helper.sh
- qa/common/json.sh
If running on opensuse-tumbleweed, use ses7/octopus/pacific semantics.
> qa: support opensuse-tumbleweed

- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Until now we were relying on "ceph fs volume create" to create the mds
service (we use the word "service" here in the cephadm sense), but
apparently it no longer does that.
Explicitly deploy the mds service/daemons by compiling a service spec
file and running "ceph orch apply" on it.
> ceph_salt_deployment: explicitly create mds service

- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
**Depends on: https://github.com/ceph/ceph/pull/35667**
Exercise this new cephadm feature for the sake of the log.
---
> ceph_salt_deployment: do "ceph orch apply --dry-run"

- qa/common/common.sh
The nfs_maybe_mount_export_and_touch_file test was originally
implemented in such a way that it displayed a disturbing message even
when run in environments where the test itself was simply skipped:
master: WWWW: nfs_maybe_mount_export_and_touch_file
master: BADNESS: NO NFS NODES IN CLUSTER, YET AM RUNNING NFS-RELATED TEST
master: WWWW: nfs_maybe_mount_export_and_touch_file: SKIPPED
> qa/common: do not print BADNESS message when test is being skipped

- seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
If the user gives --stop-before-deepsea-stage=0, then we don't want to
run even the "pre_stage_0" script.
> deepsea_deployment: really stop before Stage 0

- contrib/standalone.sh
In order to work around a regression in vagrant, we were forced in
56ca70ad243e14d849cd289858cff02746cac59a to make "sesdev create" always
return exit status 0. This had the side effect of breaking failure
detection in contrib/standalone.sh.
Fortunately, "sesdev qa-test ..." still returns non-zero on failure, so
we take advantage of that to detect failed deployments (first commit of the PR).
In the second commit, we implement a special `run_create_cmd` function
for running `sesdev create`. The function is similar to `run_cmd`, except
it captures the output in a temporary file and greps that file for the string
"Bailing out" to detect failures, instead of relying on the exit status.
> contrib/standalone.sh: adapt to create always returning 0

- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Since https://github.com/ceph/ceph-salt/pull/386, ceph-salt `/containers/image/ceph`config was moved to `/cephadm_bootstrap/ceph_image_path`.
> ceph-salt: Fix ceph image path config

- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
During integration testing we found that ceph_salt_deployment.sh always
waits for OSDs to appear, except in one test case:
sesdev create ses7 --roles [admin,master,bootstrap,storage,mon,mgr]
In this case, since there are no gateways, the "wait for OSDs to appear"
routine was not triggered.
This commit revamps the conditionals so the provisioning script always
waits for the OSDs to appear (if there are any OSDs).
> ceph_salt_deployment: always wait for OSDs to appear

- seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
The SES7 Deployment Guide says to run "ceph fs volume create" **AFTER**
the MDSs are functional. That means we have to wait.
Without this patch, we were getting the expected number of MDSs, but
they would end up on different nodes than specified in the service spec
yaml.
> ceph_salt_deployment: deploy MDSs according to documentation

- contrib/standalone.sh
When a test failed, the config.yaml that was created for testing
purposes was being left behind.
> contrib/standalone.sh: remove config.yaml even when failing

- seslib/constant.py
- seslib/deployment.py
If https://github.com/ceph/ceph-salt/pull/383 is merged, bootstrap minion will no longer be required to have the admin role.
> Bootstrap minion no longer required to have admin role

- seslib/constant.py
- seslib/deployment.py
- seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
- seslib/templates/salt/ceph-salt/deployment_day_2.sh.j2
- seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
- seslib/templates/salt/provision.sh.j2
We are distinguishing between Day 1 (bootstrapping) and Day 2, so it
makes sense to have these separate in sesdev as well.
> Split ceph_salt_deployment.sh into two

- qa/common/common.sh
- qa/health-ok.sh
- seslib/deployment.py
- seslib/templates/salt/ceph-salt/deployment_day_2.sh.j2
- seslib/templates/salt/cluster_json.j2
- seslib/templates/salt/qa_test.j2
- seslib/templates/sync_clocks.j2
With this PR, nodes that have the "prometheus" role will get
a "prometheus" service deployed.
References: https://github.com/SUSE/sesdev/issues/354
Fixes: https://github.com/SUSE/sesdev/issues/417
---
> ceph_salt: deploy and smoke-test Prometheus

- contrib/standalone.sh
Instead of complaining and refusing to run, if a config.yaml exists and
is empty (meaning we don't care about it), just delete it and continue
as if it never existed.
> contrib/standalone.sh: wipe empty config.yaml

- qa/common/common.sh
- qa/health-ok.sh
- seslib/deployment.py
- seslib/templates/salt/ceph-salt/deployment_day_2.sh.j2
- seslib/templates/salt/cluster_json.j2
- seslib/templates/salt/qa_test.j2
With this PR, nodes that have the "grafana" role will get a "grafana"
service deployed not only in {nautilus, ses6}, but in {octopus,
ses7, pacific} as well.
Fixes: https://github.com/SUSE/sesdev/issues/474
References: https://github.com/SUSE/sesdev/issues/354
> ceph-salt: deploy and smoke-test Grafana

- contrib/standalone.sh
- sesdev/__init__.py
- seslib/box.py
- seslib/constant.py
- seslib/deployment.py
- seslib/exceptions.py
- seslib/settings.py
This is a continuation of the work started by @dcermak in #453 
The idea is to use official Vagrant Boxes (from Vagrant Cloud) when available.
There is some complexity involved, because the official boxes have hard-coded box names, while `sesdev` expects its boxes to **not** have a box name. To overcome this, this PR aspires to implement a box aliasing system.
> Support official Vagrant boxes from Vagrant Cloud

- seslib/deployment.py
- seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
When there are multiple possibilities for
/time_server/subnet
/cephadm_bootstrap/mon_ip
ceph-salt has no way of knowing which one is "correct", and chooses
effectively at random.
Fixes: https://github.com/SUSE/sesdev/issues/467
> ceph-salt: set some network-related config params explicitly

- qa/common/common.sh
- qa/health-ok.sh
- seslib/deployment.py
- seslib/templates/salt/ceph-salt/deployment_day_2.sh.j2
- seslib/templates/salt/cluster_json.j2
- seslib/templates/salt/qa_test.j2
With this PR, nodes that have the "alertmanager" role will get an
"alertmanager" service deployed not only in {nautilus, ses6}, but in
{octopus, ses7, pacific} as well.
The commit also implements an alertmanager smoke test, parts
of which work on {nautilus, ses6} as well.
Fixes: https://github.com/SUSE/sesdev/issues/479
References: https://github.com/SUSE/sesdev/issues/354
> ceph-salt: deploy and smoke-test alertmanager

- seslib/templates/zypper.j2
On SLE-15-SP2, rbd-nbd should now be a part of the Base System module.
References: https://jira.suse.com/browse/SLE-11021
> zypper: install rbd-nbd on all Leap 15.2/SLE-15-SP2 nodes

- README.md
- sesdev/__init__.py
- seslib/constant.py
- seslib/deployment.py
- seslib/exceptions.py
- seslib/settings.py
- seslib/templates/apt.j2
- seslib/templates/provision.sh.j2
- seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
- seslib/templates/ubuntu/provision.sh.j2
With this commit, one can do, e.g.:
sesdev create octopus --os ubuntu-bionic
This will attempt to complete a Day 1 deployment (up to and including
"cephadm bootstrap") but Day 2 is not implemented yet, so sesdev roles
other than "master" and "bootstrap" are ignored in this initial
implementation.
https://github.com/SUSE/sesdev/issues/485
---
TO DO:
> Add ability to use Ubuntu "Bionic Beaver" 18.04

- seslib/templates/caasp/master.sh.j2
SUSE config files need special labels for Rook deployment that were added at https://github.com/SUSE/rook/commit/0efbe62733567a41e84c6d26215e41dccbfac365 .
This PR assign `any` label to all nodes so Rook will deploy services on all nodes.
> add label for ses deployment on caasp

- qa/common/common.sh
- qa/health-ok.sh
- seslib/templates/salt/qa_test.j2
This bug may take a long time to fix, so disable the test in the meantime so it doesn't increase the number of integration test failures.
References: https://github.com/SUSE/sesdev/issues/491
> qa/nfs: do not attempt to mount NFS export on "pacific"

- seslib/deployment.py
self.vagrant_box is only expected to be set when creating a new
deployment.
Fixes: https://github.com/SUSE/sesdev/issues/487
> deployment: do not assert if starting an existing deployment

- seslib/deployment.py
Its not possible to use rsync between 2 remotes.
This code tries to do the same as the block after it,
so we can simply remove it.
Signed-off-by: Tiago Melo <tmelo@suse.com>
> replace-mgr-modules: Fix nautilus mgr copy

- README.md
- contrib/standalone.sh
- sesdev/__init__.py
- seslib/deployment.py
- seslib/settings.py
- seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
- seslib/templates/salt/provision.sh.j2
---
If `--ipv6` option is used when creating `pacific`, `octopus` or `ses7` environment, IPv6 addresses will be configured:
> Add support for IPv6

- README.md
- sesdev/__init__.py
- seslib/deployment.py
- seslib/settings.py
- seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
In order to deploy a cluster with messger v2 encryption we need to
prioritise 'secure' over 'crc' mode or only provide secure mode.
The specific ceph options are:
- ms_cluster_mode
- ms_service_mode
- ms_client_mode
By default all of these are set to 'crc secure' which prioritises 'crc'
over full encryption.
NOTE: there are 3 mon specific options to the above (ms_mon_*_mode) that
by defaults already use 'secure crc' so they'll prefer secure mode first
over crc between the mon nodes when they speak msgr2. Which is awesome.
I could add an option to force mon "secure" too.
This patch adds 2 new flags that control msgr2 secure mode:
--msgr2-secure-mode: This sets the above 3 options to just 'secure'.
--msgr2-prefer-secure: This changes the order to 'secure crc' so secure
is prefered over crc. …
> Add new msgr2 secure options to sesdev

- qa/common/common.sh
- qa/health-ok.sh
- seslib/deployment.py
- seslib/templates/salt/ceph-salt/deployment_day_2.sh.j2
- seslib/templates/salt/cluster_json.j2
- seslib/templates/salt/qa_test.j2
With this PR, nodes that have the "node-exporter" role will get a
"node-exporter" service deployed. The "node-exporter" role is only
available in {octopus, ses7, pacific} (in {nautilus, ses6}, DeepSea
deploys the node-exporter together with Prometheus).
The commit also implements a node-exporter smoke test.
With this commit, sesdev can now deploy the full monitoring stack in
{octopus,ses7,pacific}.
Fixes: https://github.com/SUSE/sesdev/issues/354
> ceph-salt: deploy and smoke-test node-exporter

- sesdev/__init__.py
- seslib/deployment.py
Existing sesdev deployments are assumed to have completed provisioning already.
This commit eliminates the following useless and confusing lines that
vagrant outputs for each node in the deployment:
==> node2: Machine already provisioned. Run 'vagrant provision` or use the `--provision`
==> node2: flag to force provisioning. Provisioners marked to run always will still run.
> deployment: use "vagrant up --provision" to start cluster

- .pylintrc
- README.md
- contrib/standalone.sh
- sesdev/__init__.py
- seslib/deployment.py
- seslib/tools.py
From the feature request:
"If I deploy two sesdev clusters the network connection between them is
forbidden on iptables level. Sometimes we need to connect the clusters
though (I needed it for testing RBD mirroring. And I can imagine it
could be useful for testing RGW multisite or CephFS snapshots sync)."
Fixes: https://github.com/SUSE/sesdev/issues/396
> Implement "sesdev link" for linking two clusters

- qa/common/common.sh
- qa/health-ok.sh
As we know, cephadm deployments are asynchronous. In practice, this
means you issue a "ceph orch apply" command and it returns quickly,
but you have to wait for the results.
Until now, the preceding IGW wait took long enough that any remaining
daemons got deployed in the meantime. But recently we saw the following
failure in the Jenkins CI environment:
master: WWWW: number_of_services_expected_vs_orch_ls_test
master: MGR services (orch ls/expected): 1/1
master: MON services (orch ls/expected): 1/1
master: MDS services (orch ls/expected): 1/1
master: RGW services (orch ls/expected): 1/1
master: NFS services (orch ls/expected): 1/1
master: IGW services (orch ls/expected): 1/1
master: Prometheus services (orch ls/expected): 1/1
master: Grafana services (orch ls/expected): 0/1
master: …
> qa: wait for grafanas to show up before counting them

- README.md
- contrib/standalone.sh
- sesdev/__init__.py
- seslib/exceptions.py
This is needed to implement "ad hoc" test scripts, such as the script
for setting up and testing RGW Multisite between two sesdev clusters.
Fixes: https://github.com/SUSE/sesdev/issues/505
---
TO DO:
> Implement "sesdev show DEP_ID --nodes-with-role=ROLE"

- contrib/deepsea_drive_replace.sh
Contributing this test script in hopes of helping to reproduce certain
SES6 CI failures (i.e., those involving the drive replacement test).
> contrib/deepsea_drive_replace.sh: new test script

- qa/common/common.sh
- qa/common/helper.sh
In SES7 it currently takes longer than five minutes for the cluster to
become healthy, but this is not considered a bug.
> qa: wait longer for cluster to become healthy

- sesdev/__init__.py
- sesdev/box.py
- seslib/box.py
- seslib/exceptions.py
- seslib/tools.py
- tests/test_is_a_glob.py
With this commit, "sesdev box list" and "sesdev box remove" accept
globs. In the former, the argument is optional.
Examples:
```
sesdev list                              lists all boxes (that have been downloaded)
sesdev list \*                           same as "sesdev list"
sesdev remove                            ERROR (missing mandatory argument)
sesdev remove \*                         removes all boxes
sesdev list o\*                          lists all boxes whose dealiased name starts with "o"
sesdev remove o\*                        removes all boxes whose dealiased name starts with "o"
sesdev list leap-15.2                    ("leap-15.2" is an alias) lists the dealiased box
sesdev remove leap-15.2                  ("leap-15.2" is an alias) removes the dealiased box
sesdev remove …
```
> Make "sesdev box list" and "sesdev box remove" accept globs

- sesdev/__init__.py
- seslib/deployment.py
- seslib/settings.py
- seslib/templates/provision.sh.j2
When --fqdn is given to any "sesdev create" command:
"hostname" will return FQDN
"hostname -s" will return short hostname
Default behavior (--no-fqdn) is:
"hostname" returns short hostname
"hostname -f" returns FQDN
---
TO DO:
> create: implement --fqdn option

- seslib/constant.py
- seslib/deployment.py
- seslib/settings.py
- seslib/templates/zypper.j2
Some of the repos that we were adding to all deployments were needed
only to support "makecheck". Having them in all deployments can mask
product bugs.
References: https://bugzilla.suse.com/show_bug.cgi?id=1177245
> Add makecheck-specific repos only in "sesdev create makecheck"

- README.md
- seslib/templates/cephadm/deployment_day_2.sh.j2
When the user provides --fqdn, "hostname" will return the FQDN and, in
that case, we'd better give cephadm FQDNs if we want it to continue
being nice to us.
> cephadm/deployment_day_2: specify FQDN when appropriate

- seslib/templates/zypper.j2
This RPM is supposed to get installed automagically when ceph-common is
installed.
References: https://bugzilla.suse.com/show_bug.cgi?id=1177432
Fixes: https://github.com/SUSE/sesdev/issues/524
> templates/zypper: do not install supportutils-plugin-ses in SES[567]

- seslib/constant.py
constant: add missing SLE-15-SP2 Product repo
We have the Product repo for SLE-15-SP1, but had inadvertently omitted
it for SLE-15-SP2.
---
constant: add SLE-15-SP[12] Product Update repos
We had the Product "POOL" repos, but their "UPDATE" counterparts were
missing.
> constant: add missing SLE-15-SP[12] Product repos

- sesdev/__init__.py
- seslib/constant.py
- seslib/deployment.py
- seslib/exceptions.py
- seslib/templates/Vagrantfile.j2
- seslib/templates/zypper.j2
In its current form, this command only supports the following configurations:
* nautilus -> octopus
* ses6 -> ses7
The command takes both a DEP_ID and a NODE. It upgrades only one node, not an
entire cluster!
What will happen when I issue this command?
* old repositories will be wiped out
* new repositories will be added
* zypper dup
Fixes: https://github.com/SUSE/sesdev/issues/527
---
TO DO:
> Implement "sesdev upgrade" subcommand

- sesdev/__init__.py
- seslib/deployment.py
This requires a NODE and only knows how to reboot a single node, not
a whole cluster.
Fixes: https://github.com/SUSE/sesdev/issues/528
> Implement "sesdev reboot DEP_ID NODE" command

- sesdev/__init__.py
- seslib/exceptions.py
The exit code is optional, but we guarantee it is always there
in the args list of the Exception object.
When the code is present, have the sesdev entrypoint return it
to the calling shell.
Fixes: https://github.com/SUSE/sesdev/issues/537
> exceptions: have SesDevException return optional exit code

- seslib/deployment.py
- seslib/exceptions.py
deployment: raise exception when node does not come back from reboot
This part was overlooked in the rush to merge
0b2feb96c07428d28b54dd1ff471d3424ddb7181
---
deployment: wait for rebooted node to complete boot sequence
Once we regain SSH access, poll "systemctl is-system-running" until it
starts to succeed. This makes it more likely that the "sesdev reboot"
command won't return until the VM has really finished booting up.
> deployment: wait for rebooted node to complete boot sequence

- seslib/templates/helper_scripts.j2
- seslib/templates/provision.sh.j2
For upgrade testing, we need to be able to easily determine (via "sesdev ssh")
whether a node is running a particular OS.
> provision.sh: add helper_scripts Jinja template

- contrib/upgrade-demo-ses6-to-ses7.sh
This script demonstrates how to create an upgradeable SES6 cluster
and then upgrade it to SES7.
Fixes: https://github.com/SUSE/sesdev/issues/533
---
NOTE: To run successfully, this PR needs the following PRs:
> contrib/upgrade-demo-ses6-to-ses7.sh: add upgrade demo script

- sesdev/__init__.py
The --filestore option stopped working due to a regression.
Fixes: 81c2e6f38f64f8302b9dbf82aa1a63f67a40a4c3
> sesdev: fix --filestore

- setup.cfg
Overlooked this when I moved deployment_day_2.sh.j2 :-(
Fixes: b62836e53bdfe98367e92387d374beb42e7b1c2b
> setup.cfg: include seslib/templates/cephadm/ directory in packaging

- seslib/templates/salt/deepsea/nautilus_pre_stage_0.sh.j2
For a long time, sesdev was patching the DeepSea code. This was needed
because, in sesdev clusters, one of the hosts was called "admin" and the
MDS doesn't like this.
Now that sesdev is no longer calling hosts "admin", the patch can be
dropped.
> deepsea/nautilus_pre_stage_0.sh: refrain from patching DeepSea

- sesdev/__init__.py
If one uses type=bool on a switch style flag (like --error/--no-error)
click6 only considers this a bool flag if type is None. Flags like that
default to type bool though, so just let click find out on its own.
Click7 can handle explicit type=bool but also deducts it just fine.
Fixes: #549
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
> sesdev --devel flag: let click deduct type

- seslib/templates/caasp/master.sh.j2
With this PR it will be possible to access Ceph Dashboard right after creating an SES deployment on CaaSP:
```
$ sesdev create caasp4 --deploy-ses
...
master: Access ceph dashboard at: https://192.168.121.240:8443/
master:     Ceph dashboard username: admin
master:     Ceph dashboard password: 103c:G#$O(<bsch9n5R/
...
```
> Expose Ceph Dashboard on CaaSP SES deployment

- sesdev/__init__.py
- seslib/deployment.py
- seslib/settings.py
- seslib/templates/provision.sh.j2
- seslib/templates/zypper.j2
Until now, if AppArmor was active in the VM image, sesdev gave you no
way of deactivating it.
Fixes: https://github.com/SUSE/sesdev/issues/136
> Implement --no-apparmor option

- sesdev.spec
Without this, the installed sesdev-qa version lags behind the sesdev
version because the user will typically do
zypper update sesdev
instead of
zypper update sesdev sesdev-qa
(And it's unreasonable to expect users to remember that they should do
the latter and not the former!)
> spec: pin sesdev-qa version to sesdev version

- seslib/constant.py
- seslib/templates/zypper.j2
download.nue.suse.com is accessible to a wider range of people than
download.suse.de, but otherwise equivalent.
> constant,zypper: use download.nue.suse.com instead of download.suse.de

- seslib/templates/cephadm/deployment_day_2.sh.j2
It came to my attention that sesdev was using an unsupported
and undocumented procedure ("ceph fs volume create") to create
the CephFS.
> deployment_day_2.sh: create CephFS using documented procedure

- tox.ini
When running "tox", we recently started to see:
lint run-test: commands[0] | pylint sesdev
WARNING: test command found but not installed in testenv
cmd: /home/smithfarm/src/ceph/smithfarm/sesdev/venv/bin/pylint
env: /home/smithfarm/src/ceph/smithfarm/sesdev/.tox/lint
Maybe you forgot to specify a dependency? See also the allowlist_externals envconfig setting.
DEPRECATION WARNING: this will be an error in tox 4 and above!
To make matters worse, part of the message was displayed in RED LETTERS, which
ruined my day, so I decided to push this fix.
> tox.ini: add "allowexternals = pylint"

- sesdev/__init__.py
- seslib/deployment.py
- seslib/settings.py
- seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
- seslib/templates/salt/deepsea/nautilus_policy.cfg.j2
- seslib/templates/salt/deepsea/nautilus_pre_stage_1.sh.j2
- seslib/templates/salt/deepsea/ses6_pre_stage_1.sh.j2
Currently this only works with 'nautilus' and 'ses6' deployments.
> Implement --rgw-ssl option for deploying RGWs with SSL enabled

- seslib/constant.py
- seslib/deployment.py
- seslib/settings.py
- seslib/templates/zypper.j2
In certain cases, e.g. when installing DeepSea from source on SES6, additional
repos ("SES6 Internal Media", "Developer Tools Module", etc.) are needed to
satisfy dependencies.
We are already carrying code for "sesdev create makecheck" which adds several
additional repos, but this code can not be easily reused to address the issue.
Fixes: https://github.com/SUSE/sesdev/issues/559
---
To Do:
> zypper: add repos when needed

- contrib/standalone.sh
- seslib/constant.py
- seslib/deployment.py
- seslib/settings.py
Before this commit, "sesdev create ses7 --product" would use registry.suse.de,
which only has the devel container image. That was wrong.
Fixes: https://github.com/SUSE/sesdev/issues/560
> ses7: use product container image when --product given

- seslib/constant.py
Now that SES7 is a released product, it is receiving maintenance updates and we
will need to always have the SES7 Update repo available.
> seslib/constant.py: add SES7 Update repo

- qa/common/common.sh
- qa/health-ok.sh
- seslib/deployment.py
- seslib/templates/provision.sh.j2
- seslib/templates/zypper.j2
It came to my attention that coredump capturing might not be enabled by default
in sesdev clusters.
> provision: enable coredumps

- seslib/templates/provision.sh.j2
Only SES7 -- {octopus, ses7, pacific} to be precise -- uses systemd-journald for
logging. So make the related adjustments only on those deployment versions.
> provision.sh: persist systemd journal in SES7 only

- seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
In order to be able to simulate administration tasks like adding nodes to
a cluster, we need to make it easy for sesdev users to create deployments that
have "extra" nodes.
Before this change, we had to specify the "extra" node's roles like this:
[client]
Now nodes with no roles at all will be treated the same way when it comes to
assigning the "cephadm" ceph-salt role.
> ceph-salt: no cephadm for nodes with no sesdev roles

- sesdev.spec
Commit e1fcf95dd7bc43f7b0881288228b74ca10a0b440 added a new file qa/common/rgw.sh
but neglected to include it in the sesdev-qa RPM. This patch rectifies that
oversight.
NOTE: this only happens when sesdev is installed from the RPM package
> sesdev.spec: fix missing qa/common/rgw.sh

- sesdev/__init__.py
"zypper addrepo" provides two ways of specifying a repo:
1. "zypper addrepo URL_OF_REPO_DIRECTORY REPO_NAME"
2. "zypper addrepo URL_OF_REPO_FILE"
Until now, sesdev only supported repo directory URLs, which was confusing for
users.
With this commit, sesdev also supports repo file URLs. In other words, the
following two variants will lead to the same result:
--repo http://download.suse.de/ibs/Devel:/Storage:/6.0:/Test/SLE_15_SP1/
--repo http://download.suse.de/ibs/Devel:/Storage:/6.0:/Test/SLE_15_SP1/Devel:Storage:6.0:Test.repo
Before, only the first variant would work. The second one would produce an
error.
---
TO DO
> sesdev: support custom repo URLs pointing to .repo file

- qa/common/common.sh
- qa/health-ok.sh
- seslib/templates/provision.sh.j2
- seslib/templates/zypper.j2
provision.sh: include zypper repo setup in --no-provision
Recently a --no-provision feature was added to provide a way to quickly
bring up a VM. But in order for that feature to be useful, the VM should
have the same repos as in a full deployment.
---
zypper: be more careful when installing systemd-coredump
Due to the way Kiwi builds SLE Vagrant Boxes, the versions of packages
pre-installed in the Vagrant Box may be newer than the versions of the same
packages in the "channels" (i.e., in the zypper repos that are added after the
VMs start).
Work around this by force-installing systemd, udev, etc. from the repos.
This has the drawback of putting the system into a state where "zypper ps -s"
reports that it needs a reboot.
Fixes: …
> zypper: be more careful when installing systemd-coredump

- sesdev/__init__.py
Though the replacement code looks like it was written by a simpleton (which it
was), it has two advantages over the code it is replacing:
1. it's easier to understand
2. it passes pylint
Fixes: https://github.com/SUSE/sesdev/issues/580
> sesdev: replace fancy list comprehension with simpleton code

- seslib/templates/cephadm/deployment_day_2.sh.j2
This command was added to the upstream doc in this PR [1],
and it fixes the issue with creating a rgw bucket via dashboard
(InvalidLocationConstraint error).
[1] https://github.com/ceph/ceph/pull/36496
Signed-off-by: Mykola Golub <mgolub@suse.com>
> cephadm: add 'period update' in radosgw deployment

- contrib/standalone.sh
- seslib/templates/zypper.j2
The SLE-12-SP3 images are now being built with a python package that is even
newer than what is in the SLE-12-SP3 LTSS channel.
Work around this by deleting python and then reinstalling it from the LTSS
channel repo.
> zypper.j2: remove Python 2 even on SLE-12-SP3

- sesdev/__init__.py
- seslib/constant.py
- seslib/deployment.py
Before this patch, the user needed to give both --deepsea-repo
and --deepsea-branch options. If only one was given, sesdev was
silently ignoring it.
Fixes: https://github.com/SUSE/sesdev/issues/583
> deployment: saner processing of --deepsea-repo, --deepsea-branch

- README.md
- sesdev/__init__.py
- seslib/constant.py
Attempt to workaround:
Bug 1183740 - ceph octopus 15.2.9 fails to deploy rgw and nfs
Works-around: https://bugzilla.opensuse.org/show_bug.cgi?id=1183740
> constant.py: drop nfs from octopus default roles

- seslib/constant.py
- seslib/templates/salt/deepsea/nautilus_pre_stage_4.sh.j2
In Nautilus release 14.2.17, upstream changed the syntax of the command for
changing the dashboard password.
This commit adapts sesdev to this change.
Fixes: https://github.com/SUSE/sesdev/issues/588
> nautilus_pre_stage_4.sh.j2: adapt to syntax change

- qa/common/json.sh
As of Nautilus 14.2.17, the JSON data structure produced by
ceph status --format json
changed in a way that broke sesdev's number_of_nodes_actual_vs_expected_test for
nautilus clusters.
The new format is:
master:~ # ceph status --format json | jq -r '.monmap'
{
"epoch": 1,
"min_mon_release_name": "14",
"num_mons": 1
}
This commit fixes the issue by adapting the json_total_mons function to this 
change in Ceph's behavior.
> qa/common/json.sh: adapt to change in ceph status json format

- seslib/templates/zypper.j2
Large swathes of Python 3 may come preinstalled in the Vagrant Box.
There is no guarantee that the version number of these preinstalled RPMs
will match the version number of other Python 3 RPMs that we get from
the repos.
This is a known design flaw (bug) in how OBS/Kiwi builds images: i.e., it
takes RPMs from the codestreams and not from the distribution channels.
(That's just a very brief -- even cryptic -- statement of the problem,
but it will have to do for this commit message.)
Work around this issue by prophylactically removing the Python 3 that is
preinstalled in the Vagrant Box. Later, the Python 3 from the
distribution channels will be pulled in via the dependency chains of the
various RPMs we install.
> zypper: remove python3-base if it's installed

- contrib/nukevolz.sh
When newer versions of boxes are pulled from Vagrant Cloud, the older
versions do not get removed from vagrant-libvirt default pool.
This causes the directory /var/lib/libvirt/images to bloat over time,
as it fills up with obsolete images pulled from Vagrant Cloud.
To recover the wasted disk space, one can now do:
$ sesdev destroy -f '*'
$ sh contrib/nukevolz.sh
References: https://github.com/SUSE/sesdev/issues/591
---
TO DO:
> contrib/nukevolz.sh: primitive script to recover wasted disk space

- seslib/templates/cephadm/deployment_day_2.sh.j2
- seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
As of Nautilus v14.2.20 and Octopus v15.2.11, clusters intentionally come up in
HEALTH_WARN (AUTH_INSECURE_GLOBAL_ID_RECLAIM) and to achieve HEALTH_OK we have
to disallow this insecure feature.
> templates: disallow global ID reclaim

- seslib/deployment.py
- seslib/templates/provision.sh.j2
77506e5e7211e998737b4ce0e058c148cbb771bf
deployment: run "vagrant up" with --no-destroy-on-error
Up to Vagrant 2.2.9, --no-destroy-on-error was the default and everything was
fine.
Then Vangrant 2.2.10 changed the default to --destroy-on-error. Since I was
ignorant of this option, I worked around it by merging
55314a49fb94c08a7681b72398eee33aaf9edef0 which ensured that the provisioner
script exits with status code 0 even when there is an error (that tricked
Vagrant into thinking the script succeeded, so it did not destroy the VMs when
the script failed).
Now that I know about this option, it makes sense to run with
--no-destroy-on-error since we don't want Vagrant to destroy VMs during
provisioning in any case (since it is assumed that we want to go in and debug to
determine why the …
> provision.sh: try harder to ensure hostname is installed

- sesdev/__init__.py
- seslib/constant.py
- seslib/templates/makecheck/provision.sh.j2
Since "pacific" now corresponds to "ses7p", and since "ses7p" will run on
SLE-15-SP3, we now want "pacific" to run on openSUSE Leap 15.3 (the openSUSE
equivalent of SLE-15-SP3).
---
sesdev: accept "leap-15.3" as an argument to "--os"
Otherwise we get
Error: Invalid value for '--os': 'leap-15.3' is not one of 'leap-15.1',
'leap-15.2', 'tumbleweed', 'sles-12-sp3', 'sles-15-sp1', 'sles-15-sp2',
'ubuntu-bionic'.
---
provision.sh: have "makecheck" run scripts with "bash -x"
Instead of patching the scripts to add "set -x", we can simplify the command by
explicitly running the scripts with "bash -x".
> constant: make "vagrant create pacific" use Leap 15.3

- seslib/templates/zypper.j2
When we install basic packages, we want just those packages and their hard
dependencies. We do not need or want any soft dependencies of those packages or
of their dependencies.
> templates/zypper: install basic packages with --no-recommends

- seslib/deployment.py
- seslib/settings.py
`--stop-before-cephadm-boostrap` didn't work because the argument wasn't part of the code that reads the arguments and creates the context out of that. The context is then used to generate the templates (Vagrantfile and deployment scripts). This means that the switch never reached the conditions in the Jinja templates and was therefore technically ignored.
> Fix --stop-before-cephadm-bootstrap

- seslib/constant.py
avoid failures on less reasonable (slow) hardware
Signed-off-by: Michael Fritch <mfritch@suse.com>
> sesdev: increase timeout in seconds

- seslib/templates/cephadm/deployment_day_2.sh.j2
At some point, upstream obviously changed the syntax of the "ceph nfs cluster
create" command in octopus, thereby breaking "sesdev create pacific" and "sesdev
create ses7".
Later, this syntax change got reverted [1], but since this revert was made
possible by a big feature [2], so far it has been backported only to pacific [3]
[1] https://github.com/ceph/ceph/pull/40411
[2] https://github.com/ceph/ceph/pull/37600
[3] https://github.com/ceph/ceph/pull/41005
Fixes: https://github.com/SUSE/sesdev/issues/611
> templates/cephadm/deployment_day_2: fix NFS cluster create command

- seslib/settings.py
- tests/test_parse_config_yaml.py
Replace `yaml.load` with `safe_load` to fix pycodestyle issue and ensure
using tests that `safe_load` is capable of loading the `config.yaml`
file correctly, including the ability to use the YAML reference (which
is not explicitly documented in the sesdev docs but part of YAML).
`yaml.load` has been to be used without a Loader. However it is unsafe and
has been used way too frequently, although the documentation of PyYAML
has always stated that it is unsafe.
Fixes: #618 
> pycodestyle: Fix issue with yaml.load (use safe_load)

- seslib/templates/salt/provision.sh.j2
avoid `Looped too many times` error on resource constrained hardware
Signed-off-by: Michael Fritch <mfritch@suse.com>
> provision: increase max number loops (50 -> 500)

- seslib/templates/provision.sh.j2
The previous implementation only removed bogus loopback assignments from the first line of /etc/hosts, and expected a single tab character between each field when doing the replacement.  I've since found with vagrant 2.2.19 deploying SES6 on SLE 15 SP1, that the loopback assignment is in the middle of the file, and uses spaces, not tabs.
This change makes provision.sh remove bogus loopback assignments wherever they are in the file, and it doesn't care about what kind of whitespace is used.
Signed-off-by: Tim Serong <tserong@suse.com>
> provision.sh: zealously remove bogus loopback assignments from /etc/hosts

- seslib/deployment.py
Fixes: https://github.com/SUSE/sesdev/issues/627
> deployment.py: Enable replacing MGR in `ses7p` as well.

- seslib/deployment.py
- seslib/node.py
In ses7p `ceph mgr services` returns:
{
"dashboard": "https://10.20.161.201:8443/",
"prometheus": "http://10.20.161.201:9283/"
}
While in older releases it was:
{
"dashboard": "https://node3.ses7.test:8443/",
"prometheus": "http://node3.ses7.test:9283/"
}
This change makes it work for the both cases.
Fixes: https://github.com/SUSE/sesdev/issues/622
Signed-off-by: Mykola Golub <mgolub@suse.com>
> tunnel: improve finding dashboard node

- seslib/templates/zypper.j2
Ignore Podman 2.2.1 in `octopus` as it contains an unfixed bug that, in
conjunction with using `--network=host` leads to an `/etc/hosts` entry
being added which confuses Pythons `socket.getfqdn()` function and leads
to inaccessible links in `ceph mgr services`.
Fixes: https://github.com/SUSE/sesdev/issues/633
> seslib: Ignore Podman 2.2.1 in `octopus`

- tox.ini
From previously ~15s to ~7s by utilizing more cores using the `-j0` command line argument of `pylint`.
Note: I'm using `tox -p` to start the two tox jobs in parallel, one of which is being sped up by this PR.
> tox: speed up linting

- seslib/deployment.py
- seslib/node.py
If a node has only the roles `master` and `admin`, it should not be
provisioned with disks when the command line option `--num-disks` is
given.
There was a check in place, but it was broken because the node with the
`master` role must also have the `admin` role and the check did not
account for that.
fixes: #450
> deploy: exclude dedicated master from disks

- README.md
- examples/sesdev-config.yaml
- requirements.txt
- sesdev/__init__.py
- seslib/constant.py
- seslib/deployment.py
- seslib/exceptions.py
- seslib/settings.py
- seslib/templates/cephadm/deployment_day_2.sh.j2
- seslib/templates/provision.sh.j2
- seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
- seslib/tools.py
- tests/test_container_availability.py
- tests/test_parse_config_yaml.py
By default, development container images from build.suse.de should be used, as also build.suse.de repositories are used (`--devel` is on by default). So, basically we'll be using development container images whenever we're using development repositories. The same applies to `--product`, container images from registry.suse.com will be used if `--product` is specified. 
This change also enables to customize container images for monitoring on deployment creation, as it is possible for the ceph image already.
Currently, development container images are unspecified for `ses7`, `octopus` and `pacific` deployments (just `ses7p` has received them so far).
The deployment report reveals which container images will be used. `None` means that the container images defined in our downstream fork will …
> Add downstream container images

- seslib/constant.py
Add HAProxy, Keppalived and SNMP Gateway image paths from OBS to
constants for pacific deployments.
Fixes: #640
> constants: add haproxy, keepalived and snmp images

- Jenkinsfile.integration
Add Leap-15.3 to possible OSs to build on.
While the `vagrant-libvirt` package is broken in
https://download.opensuse.org/repositories/Virtualization:/vagrant/openSUSE_Leap_15.2,
this may be used to run integration tests on Leap-15.2. It will also
come in handy when making sure that sesdev actually works on newer leap
skews.
> ci: add leap 15.3

- setup.cfg
After bootstrap of a newly installed clone:
```
$ sesdev create ses7
Traceback (most recent call last):
File "/root/src/github.com/mgfritch/sesdev/venv/bin/sesdev", line 33, in <module>
sys.exit(load_entry_point('sesdev', 'console_scripts', 'sesdev')())
File "/root/src/github.com/mgfritch/sesdev/venv/bin/sesdev", line 25, in importlib_load_entry_point
return next(matches).load()
File "/usr/lib64/python3.8/importlib/metadata.py", line 77, in load
module = import_module(match.group('module'))
File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
File "<frozen importlib._bootstrap>", line 991, in _find_and_load
File "<frozen …
```
> add missing `requests` module to the python venv

- sesdev/__init__.py
- seslib/deployment.py
- Show subnets in CIDR notation in cluster overview
- Show network addresses in cluster status view
Example:
```
│ ~/repos/sesdev │> sesdev status
Found 3 deployments:
+------------+---------+---------+-----------------------------+----------------+-----------------+
| ID         | Version | Status  | Nodes                       | Public Network | Cluster Network |
+------------+---------+---------+-----------------------------+----------------+-----------------+
| alpha-ses6 | ses6    | stopped | master, node1, node2, node3 | 10.20.55.0/24  | 10.21.3.0/24    |
| beta-ses6  | ses6    | stopped | master, node1, node2, node3 | 10.20.142.0/24 | 10.21.104.0/24  |
| ses7p      | ses7p   | running | master, node1, node2, node3 | …
```
> feature: show network addresses in status view

- seslib/deployment.py
- seslib/settings.py
- seslib/templates/Vagrantfile.j2
- seslib/templates/provision.sh.j2
- Add feature to provision additional ssh public keys to the VM's
`/root/.ssh/authorized_keys` file.
This feature allows a user to specify a list of key ids. The public keys
belonging to those ids will be fetched from the ssh agent and
provisioned to the VM's `/root/.ssh/authorized_keys` file. This allows
for better interaction with tools like `mtui`, which don't utilize
`sesdev` as ssh wrapper but still need ssh access to the VMs.
fixes: #647
> feature: provision additional ssh public keys

- seslib/templates/salt/deepsea/nautilus_pre_stage_3.sh.j2
- seslib/templates/salt/deepsea/nautilus_pre_stage_4.sh.j2
- seslib/templates/salt/deepsea/ses6_pre_stage_3.sh.j2
- seslib/templates/salt/deepsea/ses6_pre_stage_4.sh.j2
By default, DeepSea will set a random password for the dashboard admin user, by calling salt's random.get_str function:
https://github.com/SUSE/DeepSea/blob/64cf6c350da1214cc0bbcc11e372b25cbd29d35a/srv/salt/ceph/dashboard/default.sls#L2
It's possible for the string returned to include characters that break the parsing of the above jinja template and/or screw up the line that echoes the password into `ceph dashboard ac-user-create`.  We can work around this potential problem by setting the admin password to "admin" in advance of stage 3, using the dashboard_creds grain.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1200794
Signed-off-by: Tim Serong <tserong@suse.com>
> ses6: set dashboard admin password via grain

- Jenkinsfile.integration
Here we drop https://download.opensuse.org/repositories/Virtualization:/vagrant repo because from leap 15.3 vagrant-libvirt is included in stock version.
Also we drop removing conflicting packages because it is not necessary anymore. 
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
> jenkins: fix ci and add leap 15.4

- sesdev/__init__.py
- seslib/constant.py
- seslib/deployment.py
- seslib/zypper.py
- Add command for generating maintenance test report data on a running
cluster.
When testing maintenance updates for various packages, certain
informations need to be collected and entered into the final report.
Thus far, the information was largely collected by hand from various
commands run against the cluster.
This change adds a new sub command, which aggregates this information
and prints it ready for copy-and-paste to the console.
Included in this information is
- The command and configuration used to create the test cluster
- Basic information about the resulting cluster layout
- A list of packages and installation statuses from each relevenat
repo on each host
- The Ceph cluster status
> feature: generate maintentance test reports

- seslib/templates/zypper.j2
Install updates from custom repos, if any are available, for all
packages that are installed before starting the installation procedure
for ceph.
This ensures that when custom repos provide e.g. new versions of salt
or zypper those versions are installed before the cluster is installed.
This functionality is useful for maintenance tests against packages used
during the installation of ceph.
> install: install updates from custom repos

- sesdev/__init__.py
- seslib/constant.py
- Create a test deployment with auto-generated settings from a
maintenance id
Maintenance update package tests rely on a consisted test environment to
produce reliable results. This change codifies the settings used to
generate such an environment, so that operator errors are minimized.
This convenience command takes a maintenance id of the form
'S:M:xxxxx:yyyyyy' and generates a cluster with the right additional
repos and settings for reliable testing.
> feature: create test deployment from maintenance id

- sesdev/__init__.py
Fix typo in options for `--os` flag. A missing comma accidentally joined
the options `sles-15-sp3` and `ubuntu-bionic`.
> fix: typo in options for `--os` flag

- sesdev/__init__.py
- seslib/deployment.py
Add list of configured repos to the maintenance report. This is useful
to trace back which repo url a specific package listed in the same
maintenance report came from. It will also be useful in the future to
ensure a package update test actually installed the expected packages
and not packages from a different repo.
> maintenance report: add list of repos

- sesdev/__init__.py
- seslib/deployment.py
Include ceph version information in the maintenance report. This is
useful to ensure that at the end of the test workflow the versions
running in the cluster (both package- and container-versions) are as
expected.
> maintenance report: include ceph versions

- .github/workflows/tox.yaml
- tox.ini
This fixes python tox and lint failures, also we drop 3.8 since it cannot be found anymore in Leap 15.4
> worklfows/tox: update action uses

- Jenkinsfile.integration
Add parameter for custom JCS repo to allow testing fixes to JCS before deploying to production
> ci: parametrize jcs repo

- qa/common/common.sh
This is related to https://github.com/SUSE/sesdev/issues/672. When running `sesdev create ses7p --qa-test`, the
make_salt_master_an_admin_node_test function will try to install ceph-common.  If we're suffering from subtle version drift between ceph-common and ceph-base from different repos, this will fail with something like:
```
Problem: the installed ceph-base-16.2.9.536+g41a9f9a5573-150300.3.3.1.x86_64 requires 'ceph-common = 16.2.9.536+g41a9f9a5573-150300.3.3.1', but this requirement cannot be provided
Solution 1: deinstallation of ceph-base-16.2.9.536+g41a9f9a5573-150300.3.3.1.x86_64
Solution 2: do not install ceph-common-16.2.9.536+g41a9f9a5573-150300.6.3.1.x86_64
Solution 3: break ceph-base-16.2.9.536+g41a9f9a5573-150300.3.3.1.x86_64 by ignoring some of its dependencies
```
This is …
> qa: fix make_salt_master_an_admin_node_test and NFS tests

- README.md
- sesdev/__init__.py
- seslib/constant.py
- seslib/deployment.py
- seslib/exceptions.py
- seslib/settings.py
- seslib/templates/k3s/provision.sh.j2
- seslib/templates/provision.sh.j2
- setup.cfg
- tests/test_parse_config_yaml.py
This does a couple of things:
1) Lets us use `sesdev` to deploy k3s, just for the sake of having an easy way to create little VM clusters running k3s (think: arbitrary k3s dev/test playground)
2) Adds the ability to deploy rook on top of k3s, for the sake of testing rook/ceph for ongoing SES maintenance.
> Add support for deploying k3s

- README.md
- sesdev/__init__.py
- seslib/deployment.py
- seslib/settings.py
- seslib/templates/k3s/provision.sh.j2
This adds the `--deploy-longhorn` option to `sesdev create k3s`, which will make sesdev deploy Longhorn instead of Ceph.  By default it will deploy the latest released version of Longhorn on SLE 15 SP3, but this can be overridden by using the `--longhorn-version` and `--os options` respectively.
When deploying Longhorn, one extra 8GB disk will be added to each worker node mounted as ext4 under /var/lib/longhorn.  One possible area for future work is to make it use multiple disks per node.
The Longhorn UI will be made available via HTTP with no authentication.
> Add ability to deploy Longhorn on k3s

- qa/common/common.sh
The serve loop can occasionally take more than 5 min to refresh the HostCache
This avoids sporadic failures during `sesdev create ses7p --qa-test` where the service has been deployed but we need to wait a few min longer for a refresh of the HostCache before the deployed daemon will appear:
```
master: Minutes left to wait: 0
master:  iscsi daemons did not appear even after waiting 5 minutes.
Giving up.
master:
master:
master: Overall result: NOT_OK (error )
```
> Increase `ceph orch ps` wait for timeout

- qa/common/common.sh
This reworks the previous implementation to avoid use of $DEPLOYMENT_VERSION as mentioned in https://github.com/SUSE/sesdev/pull/677#issuecomment-1466193003
Fixes: 0f916017d98ebfa0ffa8fb1b0e7cfae58d2c9846
> qa: handle Octopus/Pacific NFS discrepancies (reworked)

- Jenkinsfile.integration
After looking through ceph-salt logs from previous failed Jenkins runs, and also at Volker's issue which seems to be the same thing (see https://github.com/SUSE/sesdev/issues/700), my current suspicion is that the ceph-salt executor is correctly starting `salt -G 'ceph-salt:member' state.apply ceph-salt` but is then failing to pick up some (or all) of the event notifications, which results in it returning too soon, while `cephadm bootstrap` is still running.
Assuming I'm on the right track here, let's ask `sesdev` to run that salt command directly, to remove the ceph-salt executor from the picture entirely.
> Jenkinsfile.integration: use `sesdev create --salt`

- Jenkinsfile.integration
It appears in the newer openstackclient code the new feature available starting from Python 3.7:
```
from __future__ import annotations
```
For more info see:
https://peps.python.org/pep-0563/#enabling-the-future-behavior-in-python-3-7
Since the default Python in Leap 15.4 is still 3.6, so maybe just start using the latest available 3.11 for jcs.
> Jenkinsfile.integration: use python3.11 for jcs

- README.md
The packages on OBS are very very old, and we haven't cut a new release for a long time.  In order to avoid confusion (given sesdev is not currently widely used), I've disabled package builds on OBS and removed the mention of the packages from the README in favour of just running from source.  If the situation changes in future we can always re-enable builds on OBS and revert this change.
Fixes: #705
> README.md: drop mention of packages
