SUSE/sesdev

README.md
=> README.md: tell folks to add themselves to the libvirt group

sesdev.py
=> sesdev.py: fix typo in --help

CHANGELOG.md, sesdev/__init__.py
=> Handle Ctrl+C on deployment creation

.github/workflows/linting.yml, .gitignore, .pylintrc, README.md, requirements.txt, sesdev/__init__.py, seslib/__init__.py, seslib/tools.py, setup.cfg, setup.py
This PR adds pylint and pycodestyle configurations and a github action workflow to run the linters on every push and pull-request.
=> test: run pylint and pycodestyle linters

sesdev/__init__.py, seslib/__init__.py
=> sesdev: add version column to `list` subcommand

CHANGELOG.md, README.md
Updated `README.md` on how to use an editable Python venv
Added documentation for `stop` and `destroy`
Rewrapped some overlong lines.
Signed-off-by: Lenz Grimmer <lgrimmer@suse.com>
=> README.md: Various improvements

.pylintrc, sesdev/__init__.py, seslib/__init__.py, seslib/exceptions.py, seslib/templates/Vagrantfile.j2, seslib/templates/engine/libvirt/vagrant.node.j2, seslib/templates/engine/libvirt/vagrant.provider.j2, seslib/templates/suma/suma_deployment.sh.j2, setup.cfg
Adds the "suma" role, which can be used instead of the "admin" role,
and will install SUMA and adds all other nodes to SUMA.
The SUMA node will have the salt-master, and all other nodes will
have a salt-minion each.
=> SUMA deployment in "octopus"

sesdev/__init__.py, seslib/__init__.py
Fixes: https://github.com/rjfd/sesdev/issues/20
=> If less than 3 storage nodes, increase number of disks

sesdev/__init__.py
=> Remove CLI argument off example that results in failure

seslib/__init__.py
It's not really an update repo...
=> VERSION_OS_REPO_MAPPING: better name for ses7-media1 repo

sesdev/__init__.py, seslib/__init__.py, seslib/exceptions.py, seslib/templates/engine/libvirt/vagrant.node.j2, seslib/templates/provision.sh.j2
This also exposed the domain config option.
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
=> Add option for predefined libvirt networks

seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
Fixes: https://github.com/SUSE/sesdev/issues/47
=> ceph_bootstrap_deployment: ensure minions are responding

sesdev/__init__.py
Fixes: https://github.com/SUSE/sesdev/issues/54
Signed-off-by: Jan Fajerski <jfajerski@suse.com>
=> sesdev create: fix help text

.gitignore
=> Git ignore PyCharm '.idea' directory

.pylintrc, sesdev/__init__.py, seslib/__init__.py, seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2, seslib/templates/deepsea/deepsea_deployment.sh.j2, seslib/templates/provision.sh.j2, seslib/templates/suma/suma_deployment.sh.j2
Add --qa-test option that installs and runs the qa tests added to ceph-bootstrap by https://github.com/ceph-bootstrap/pull/33
Also fix annoying transient failure https://github.com/SUSE/sesdev/issues/47
=> qa: initial qa integration

sesdev/__init__.py, seslib/__init__.py, seslib/templates/ceph-bootstrap/ceph_bootstrap_deployment.sh.j2
=> ceph_bootstrap: use "ceph-bootstrap deploy" command to run ceph-salt formula

README.md, sesdev.spec, setup.cfg
=> doc: globally change 'rjfd' to 'SUSE'

README.md, sesdev/__init__.py, seslib/__init__.py, seslib/templates/engine/libvirt/vagrant.provider.j2
Fixes: https://github.com/SUSE/sesdev/issues/70
=> Allow user to specify custom private key file for remote libvirt

sesdev.spec
These will help get sesdev past Factory review.
=> Miscellaneous spec file cleanups and bugfixes

sesdev.spec
=> spec: add Fedora-specific Requires

seslib/__init__.py
Fixes: https://github.com/SUSE/sesdev/issues/73
=> seslib: fix Ceph repos for ses5, ses6, ses7

README.md
=> README.md: make installation instructions less confusing

README.md
TOC generated using https://github.com/ekalinin/github-markdown-toc
=> README.md: add Table of Contents

README.md, sesdev/__init__.py, seslib/__init__.py, seslib/exceptions.py
Fixes: https://github.com/SUSE/sesdev/issues/91
=> Implement "sesdev scp" feature

HOWTORELEASE.md
=> HOWTORELEASE.md: tweak the commands so they actually work

seslib/__init__.py
Fixes: https://github.com/SUSE/sesdev/issues/110
=> seslib: by default, a mgr for every mon

qa/README.rst, qa/common/common.sh, qa/common/helper.sh, qa/common/json.sh, qa/common/zypper.sh, qa/health-ok.sh, sesdev.spec, sesdev/__init__.py, seslib/__init__.py, seslib/templates/Vagrantfile.j2, seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2, seslib/templates/provision.sh.j2
Part Two of "migrate qa/health-ok from ceph-bootstrap to sesdev"
=> Migrate ceph-bootstrap-qa to sesdev (part 2)

README.md
=> README.md: add "Common pitfalls" section

sesdev/__init__.py
=> seslib: fix --no-deploy-mgrs option not working

sesdev/__init__.py, seslib/__init__.py
Fixes: https://github.com/SUSE/sesdev/issues/124
=> sesdev: add --non-interactive option to "sesdev create"

README.md
=> README: add a Common Pitfall: "Storage pool not found"

README.md
=> README: add a Common Pitfall for dangling virtual networks

seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
=> ceph_salt_deployment: run "ceph-salt status" after "ceph-salt config ls"

sesdev/__init__.py, seslib/__init__.py
`Signed-off-by: Joao Eduardo Luis <joao@suse.com>`
=> seslib: remove host's virtual networks on destroy

Jenkinsfile.integration
Do a full installation when PRs are created.
=> Add Jenkinsfile.integration for PR testing

sesdev/__init__.py, seslib/__init__.py
This aims to close the issue #147
=> Add prometheus and alertmanager tunnels.

CONTRIBUTING.rst, README.md, setup.cfg, tests/test_pytest_smoke.py, tox.ini
=> tests: enable unit testing via tox

Jenkinsfile.integration
There is a Jenkins parameter for using a specific image. That
parameter is currently not used.
Fixes: #152
=> Jenkinsfile: Use configured image

README.md, seslib/__init__.py, seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Fixes: https://github.com/SUSE/sesdev/134
Fixes: https://github.com/SUSE/sesdev/135
---
To Do
=> Allow user to override parts of OS_REPOS, VERSION_OS_REPO_MAPPING, and IMAGE_PATHS

README.md
Fixes: https://github.com/SUSE/sesdev/issues/96
=> README: add "Install on Debian/Ubuntu" section

README.md, seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Depends on: https://github.com/ceph/ceph-salt/pull/121
An example is also added to README.
Fixes: #157
=> seslib: Set admin roles for octopus

README.md, seslib/__init__.py, seslib/templates/provision.sh.j2
Fixes: https://github.com/SUSE/sesdev/issues/162
=> config.yaml: enable setting of repo priority in version_os_repo_mapping

README.md, bootstrap.sh
=> Add a bootstrap.sh script and document how to use it

sesdev/__init__.py, seslib/__init__.py
Fixes: https://github.com/SUSE/sesdev/issues/174
=> Implement feature: "sesdev ssh DEP_ID NODE_ID COMMAND"

seslib/templates/provision.sh.j2
Works-around: https://github.com/ceph/ceph-salt/issues/130
=> provision.sh: Work around podman/runc issue

README.md, qa/common/common.sh, qa/health-ok.sh, seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
References: https://github.com/ceph/ceph-salt/issues/118
=> ceph_salt_deployment.sh: adapt Drive Group string to new syntax

seslib/__init__.py, seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
=> ceph_salt_deployment: fetch GitHub PRs when needed

sesdev/__init__.py, seslib/exceptions.py
Without a master role, the deployment will never succeed, so don't even
start it.
=> sesdev: fail when master role is missing

seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
=> ceph_salt_deployment: sync clocks after deployment

seslib/__init__.py
Fixes: https://github.com/SUSE/sesdev/issues/212
Fixes: a52f94eb3faa24fe1505cf8f6ded620f743d8f52
=> seslib: check bootstrap role only when it is relevant

sesdev/__init__.py, seslib/__init__.py
Signed-off-by: Kai Wagner <kwagner@suse.com>
=> Added the possibility to deploy from the master branch packages

seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Adapt the change from https://github.com/ceph/ceph-salt/pull/162
=> [AFTER https://github.com/ceph/ceph-salt/pull/162] Use quoted string to set bootstrap configs

Jenkinsfile.integration
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>
=> Multiple Jenkinsfile.intergration improvements

seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2, seslib/templates/deepsea/deepsea_deployment.sh.j2, seslib/templates/deepsea/ses5_pre_stage_0.sh.j2, seslib/templates/provision.sh.j2, seslib/templates/wait_for_minions.sh
The exact same code was used in multiple places. Take advantage of
Jinja's "include" directive to have it in only one place.
=> templates: move test.ping try-wait into a separate file

README.md, sesdev/__init__.py, seslib/__init__.py, seslib/exceptions.py, seslib/templates/Vagrantfile.j2
resolves https://github.com/SUSE/sesdev/issues/237
example ouput
```
➜  sesdev create octopus --synced-folder /home/jxs/projects/ceph:/root/ceph  test_sync --single-node
=== Creating deployment "test_sync" with the following configuration ===
1 Deployment VMs:
-- master:
- OS:               leap-15.2
[..snip..]
- synced_folder:    /home/jxs/projects/ceph -> /root/ceph
```
=> Implement feature: '--synced-folder' to nfs mount directories

contrib/standalone.sh, sesdev.spec, sesdev/__init__.py, setup.cfg
Fixes: https://github.com/SUSE/sesdev/issues/252
---
contrib/standalone.sh: do not start testing in unclean env 
---
sesdev: use prettytable to generate "sesdev list" table 
---
=> sesdev: implement "sesdev list --format json"

seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
After https://github.com/ceph/ceph-salt/pull/200
=> Rename 'ceph-salt deploy' to 'ceph-salt apply'

contrib/standalone.sh, seslib/templates/provision.sh.j2
Fixes: https://github.com/SUSE/sesdev/issues/282
=> provision.sh.j2: Properly prepare CaaSP nodes

contrib/nukenetz.sh
There are times in one's life when one must do what one must do...
=> contrib/nukenetz.sh: virtual network destruction

README.md, setup.cfg
Tumbleweed ships Click 7.
Fixes: b4de055cf3b60265f240944093ebf5383d890bb0
Fixes: https://github.com/SUSE/sesdev/issues/295
=> setup.cfg: do not break Tumbleweed RPM install

seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Companion commit to https://github.com/ceph/ceph-salt/pull/220
to preserve the current behavior.
=> ceph_salt_deployment: do not force user to change dashboard pw

seslib/__init__.py
This is will prevent pylint's too-many-public-methods error
to happen when adding few more public methods.
Signed-off-by: Tiago Melo <tmelo@suse.com>
=> seslib: convert public methods into private

contrib/nukenetz.sh, qa/common/common.sh, qa/common/json.sh, qa/health-ok.sh, sesdev/__init__.py, seslib/__init__.py, seslib/exceptions.py, seslib/templates/ceph-salt/ceph_salt_deployment.sh.j2
Fixes: https://github.com/SUSE/sesdev/issues/255
=> Implement RGW deployment in octopus, ses7

.pylintrc, README.md, sesdev/__init__.py, seslib/__init__.py, seslib/exceptions.py
Signed-off-by: Tiago Melo <tmelo@suse.com>
---
TO DO:
=> Implement replace-mgr-modules subcommand

seslib/__init__.py
At the beginning, Deployment had just one ssh method so there was no
code duplication.
Then, the scp feature was added and the ssh boilerplate options got
duplicated.
Recently, the rsync feature was added, which uses the same ssh
boilerplate options. At that point, the same exact set of boilerplate
options appeared in three different locations.
If we ever wanted to modify the boilerplate options, we would have to
modify it in at least three places. To avoid that, move the boilerplate
options into a dedicated, static method.
=> seslib: move boilerplate ssh options into a staticmethod

qa/common/common.sh
Turns out it may take some time before the "ceph orch ps" output shows
all the daemons that are expected to be running in the cluster. Add
a try-wait loop to this test.
=> qa/common: make "ceph orch ps" test more resilient

seslib/templates/provision.sh.j2
Fixes: https://github.com/SUSE/sesdev/issues/362
=> provision.sh: avoid endless while loop

seslib/templates/cluster_json.sh.j2, seslib/templates/wait_for_minions.sh.j2
=> cleanup: replace "grep | wc --lines" with "grep --count"

contrib/standalone.sh, sesdev/__init__.py, seslib/__init__.py, seslib/constant.py, seslib/log.py, seslib/settings.py
Before:
```
$ wc --lines seslib/__init__.py
2195 seslib/__init__.py
```
After:
```
$ wc --lines seslib/__init__.py
1536 seslib/__init__.py
```
---
To Do:
=> cleanup: reduce bloatedness of seslib/__init__.py

qa/common/rgw.sh
It's possible for the RGW to refuse connections even after once
accepting a connection:
master: + rgw_curl_test master
master: + set +x
master:
master: curl command for RGW ping "curl --silent --show-error http://master:80"
master: Pinging RGW (1/50) ...
master: RGW appears to be ready!
master: + set +x
master: + break
master: + curl --silent --show-error http://master:80
master: + tee /tmp/rgw_test.xml
master: curl: (7) Failed to connect to
master:  master port 80: Connection re
master: fused
master: + test -f /tmp/rgw_test.xml
master: + xmllint --format /tmp/rgw_test.xml
master: /tmp/rgw_test.xml:1: parser error : Document is empty
master:
master: ^
=> qa/common/rgw: fix curl try-wait

seslib/constant.py, seslib/templates/provision.sh.j2
It doesn't make much sense to install packages before we are finished
adding all repos.
Also run "zypper repos --details" for the log's sake.
(This PR also brings a commit that fixes a repository-related issue with "sesdev create makecheck".)
=> provision.sh: add all repos before installing packages

qa/common/common.sh, qa/common/helper.sh, qa/health-ok.sh, seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
Fixes: https://github.com/SUSE/sesdev/issues/338
Fixes: https://github.com/SUSE/sesdev/issues/386
=> ceph_salt_deployment: use mgr/nfs CLI to deploy NFS Ganesha

seslib/deployment.py
In addition to replace MGR modules, 'bin/cephadm' should also be replaced in order to test cephadm patches / PRs.
=> 'sesdev replace-mgr-modules' should also replace 'bin/cephadm'

sesdev/__init__.py, seslib/deployment.py
With this commit, the "show" subcommand gets a "--detail" option.
By default, the individual VMs section is not displayed, but it is
displayed if the user specifies --detail on the command line.
=> Improve the "show" subcommand

sesdev/__init__.py
The functions implementing functions other than "sesdev create"
and "sesdev box" were not in alphabetical order.
Putting them in alphabetical order is an easy way to improve
code readability.
=> sesdev: non-create, non-box functions in alphabetical order

seslib/templates/makecheck/provision.sh.j2, seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2, seslib/templates/salt/deepsea/deepsea_deployment.sh.j2
Either this option never got implemented, or the implementation got
lost in refactoring.
=> ceph_salt_deployment: implement "--stop_before_ceph_orch_apply"

README.md, contrib/standalone.sh, sesdev/__init__.py, seslib/deployment.py, seslib/templates/caasp/master.sh.j2
add functionality to deploy single node CaaSP cluster with ability to
deploy Rook on it
Signed-off-by: Denis Kondratenko <denis.kondratenko@suse.com>
=> single node CaaSP cluster

README.md
Add new section so I don't have to re-invent the wheel every time I need
to access the dashboard.
=> README: problems accessing dashboard on remote sesdev

README.md
This commit adds a section describing how to use sesdev to deploy
a "bare bone" cluster.
It also brings some improvements to the CaaSP/Rook section, dividing it
up into subsections and linking to it from other sections that mention
CaaSP.
=> README: bare bone cluster and CaaSP/Rook improvements

seslib/templates/salt/ceph-salt/ceph_salt_deployment.sh.j2
~~After https://github.com/ceph/ceph-salt/pull/345~~
---
=> Drop ceph-salt '/system_update' config

sesdev/__init__.py, seslib/box.py, seslib/exceptions.py, seslib/log.py
We had a way to remove a single box, but no way to blow away all boxes
at once.
=> Implement "sesdev box remove --all" feature

README.md
=> README.md: explain in more detail how to install Vagrant

seslib/constant.py
Use pacific repos instead of master.
=> Update pacific repos

seslib/templates/caasp/master.sh.j2
remove anti-affinity for mons for single node
Signed-off-by: Denis Kondratenko <denis.kondratenko@suse.com>
=> caasp4: remove anti-affinity for mons for single node

CHANGELOG.md, sesdev/__init__.py, seslib/deployment.py, seslib/settings.py, seslib/templates/provision.sh.j2
Sometimes we just want a plain VM with nothing on it...
=> Implement --no-provision option to deploy "bare" VMs

seslib/deployment.py
References: https://github.com/SUSE/sesdev/issues/511
=> deployment: do not populate public_network with "0/24"

Jenkinsfile.integration, README.md, contrib/standalone.sh, sesdev/__init__.py, seslib/deployment.py, seslib/exceptions.py
=> Implement "sesdev status" subcommand

.travis.yml, Jenkinsfile.integration, README.md, tox.ini-travis
=> tox: run pip with --use-feature=2020-resolver

seslib/templates/cephadm/deployment_day_2.sh.j2
This reverts commit 9b1d6a57e452b5cf63a5c6433e0fe74fabbcb098.
---
Testing if CI still reproduces https://tracker.ceph.com/issues/46764
=> Revert "ceph_salt_deployment: add 1-minute grace period"

seslib/templates/salt/ceph-salt/deployment_day_1.sh.j2
Adapt to https://github.com/ceph/ceph-salt/pull/439
=> Add timeserver instead of set

seslib/templates/cephadm/deployment_day_2.sh.j2
=> cephadm/deployment_day_2.sh.j2: do not fail on defective --dry-run

contrib/standalone.sh
=> contrib/standalone.sh: add --fqdn test cases

README.md
Also take this opportunity to mention CODE_OF_CONDUCT.md in the "Contributing"
section.
=> doc/README.md: add common pitfall "Failed to intialize libnetcontrol"

README.md
=> doc: add helpful details for installing on SLE-15-SP2

README.md, seslib/settings.py
Fixes: https://github.com/SUSE/sesdev/issues/563
Signed-off-by: Tim Serong <tserong@suse.com>
=> Handle image_paths_{product,devel} overrides in config.yaml

contrib/upgrade-demo-ses6-to-ses7.sh
This script was found to no longer result in a successful upgrade.
This commit attempts to restore it to working order.
=> contrib/upgrade-demo-ses6-to-ses7.sh: fix

README.md, tox.ini
=> fix tox for Python 3.8

seslib/deployment.py
=> deployment: Remove redundant codes in node network

seslib/deployment.py
=> fix pylint issues

README.md, sesdev/__init__.py, seslib/deployment.py
I've been using this for a while now and think it might also be useful for others. Although, it would also be useful for me to have it merged. It's not a full featured solution, it just enables to comfortably and automatically copy files to `root` and run an arbitrary script on each host on deployment. The custom provisioning can also be triggered after deployment for all VMs of a deployment or just one.
=> Custom provision config

seslib/constant.py
Signed-off-by: Volker Theile <vtheile@suse.com>
=> Adapt SES7P image path to latest changes

seslib/constant.py
- Uncomment and rectify ses7.1 repo urls for sles-15-sp3
=> constants: ses7.1 repo urls

seslib/deployment.py
Signed-off-by: Volker Theile <vtheile@suse.com>
=> Fix port of tunnel to Prometheus. It is running on port 9095 in ses7p.

README.md, sesdev/__init__.py, setup.cfg
- Add a command to generate shell autocompletion code
This improves usability for the command line.
fixes: #477
=> usability: add shell auto completion

seslib/deployment.py
When issued a stop command, wait for the VM to shut down (up to one
minute) before continuing.
fixes: #500
=> deployment: wait for VM to shut down

Jenkinsfile.integration
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
=> Jenkinsfile: defaults Leap 15.4

sesdev/box.py
Rediesign box removal dialogue to first check for deployments using a
vagrant box and then ask the user for confirmation. This removes
confusion when a box being used by a deployment is beign removed.
fixes: #619
=> usability: redesign box remove dialogue

Jenkinsfile.integration
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>
=> jenkins: jenkins url changed again
